### PR TITLE
inventory: Add ubuntu 2404 machines to inventory

### PR DESCRIPTION
**Pull request by Haroon-Khel**
- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

2 new machines added as per https://github.com/adoptium/infrastructure/issues/3501

### CODE REVIEW

**Comment by sxa** [comment]
I can't seem to log into the azure machine - can we get the machine set up like the other so that it allows the infra team to log in directly as root? We generally enable that on all Linux systems even if they're not provided that way.

**Review by karianna — APPROVED** [review]

**Comment by steelhead31** [comment]
@Haroon-Khel Im unable to login as root or the details in the inventory, nagios can only log in on 20.115.98.159 , can you check the nagios elements of the playbook have been run, and the user created etc?, also would you mind adding my keys, so I can check and get things added. Thanks!

**Review by steelhead31 — APPROVED** [review]
LGTM

**Comment by Haroon-Khel** [comment]
@steelhead31 The bastillion key is on both of the machine, but I do not see your key there. I have added your key to both right now

**Pull request merged**
