### PR TITLE
Playbooks: Add java 17 bootstrap to Unix, Windows and AIX playbooks

### PR DESCRIPTION
**Pull request by Haroon-Khel**
- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

ref https://github.com/adoptium/infrastructure/issues/2337

### CODE REVIEW

**Review by sxa — APPROVED** [review]
LGTM - feel free to merge once you've got the checks passing :-)

**Comment by Haroon-Khel** [comment]
I dont quite know what's causing the linter errors

```
Error: [key-duplicates] duplication of key "jdk_version" in mapping
Error: [key-duplicates] duplication of key "when" in mapping
Error: [key-duplicates] duplication of key "tags" in mapping
```

**Comment by sxa** [comment]
> I dont quite know what's causing the linter errors
> 
> ```
> Error: [key-duplicates] duplication of key "jdk_version" in mapping
> Error: [key-duplicates] duplication of key "when" in mapping
> Error: [key-duplicates] duplication of key "tags" in mapping
> ```

You're missing the ` - role: adoptopenjdk_install  # JDK18 Build Bootstrap` at the start of the new section in the UNIX top level playbook file, so it's treating the new block as part of the previous section, hence the duplicates.

**Comment by Haroon-Khel** [comment]
>You're missing the - role: adoptopenjdk_install # JDK18 Build Bootstrap at the start of the new section in the UNIX top level playbook file, so it's treating the new block as part of the previous section, hence the duplicates

Yep just saw that. Added the fix. Should be merge-able now

**Pull request merged**
