### PR TITLE
docker: add jenkinsfile to build images

### PR DESCRIPTION
**Pull request by gdams**
fixes: https://github.com/adoptium/infrastructure/issues/2145

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

Can be seen running at https://ci.adoptopenjdk.net/job/gdams-docker-infra/12/console

### CODE REVIEW

**Comment by sxa** [comment]
Looks like something has failed in that run so I won't approve yet and will let you check it out first :-)

**Review by sxa — COMMENTED** [review]
Looks like something has failed in that run so I won't approve yet and will let you check it out first :-)

**Comment by gdams** [comment]
Issue is unrelated to this PR: https://ci.adoptopenjdk.net/job/gdams-docker-infra/12/execution/node/33/log/

```bash
TASK [cmake : Download cmake] **************************************************
fatal: [localhost]: FAILED! => {"changed": false, "dest": "/tmp/cmake-3.11.4.tar.gz", "elapsed": 10, "msg": "Request failed: <urlopen error ('_ssl.c:602: The handshake operation timed out',)>", "url": "https://github.com/Kitware/CMake/releases/download/v3.11.4/cmake-3.11.4.tar.gz"}
```

**Comment by sxa** [comment]
Suggest kicking off again if it was a random network glitch and see if we can get it to completion to verify it properly.

**Comment by gdams** [comment]
@sxa https://ci.adoptopenjdk.net/job/gdams-docker-infra/13/console

**Comment by sxa** [comment]
Looks like aarch64 has failed again :-(

**Comment by sxa** [comment]
@gdams What's your recommendation for looking at the output from a particular platform in that log - with the way it's been done it's somewhat non-trivial to track down what happened on the aarch64 part of it so we should document how to to problem determination on it.

**Comment by gdams** [comment]
you can use this link to view each log https://ci.adoptopenjdk.net/job/gdams-docker-infra/12/execution/node/33/log/

**Comment by sxa** [comment]
How do you navigate to that?

**Comment by gdams** [comment]
Trying again: https://ci.adoptopenjdk.net/job/gdams-docker-infra/14/console

**Comment by gdams** [comment]
okay @sxa all problems should be fixed now: final test build https://ci.adoptopenjdk.net/job/gdams-docker-infra/17/

**Review by karianna — APPROVED** [review]
LGTM

**Comment by gdams** [comment]
Images have now been updated

Screenshot 2021-05-18 at 12 37 59

**Review by sxa — APPROVED** [review]
That one seems ot have run ok, although for some reason I'm still not seeing JDK15 under `/usr/lib/jvm` on the aarch64 image after re-pulling despite the install showing up ok in https://ci.adoptopenjdk.net/job/gdams-docker-infra/17/execution/node/31/log/ - is that pushing to the live image?

**Comment by sxa** [comment]
Shows up if I pull `adoptopenjdk/centos7_build_image:linux-arm64` explicitly, but not without the `linux-arm64` suffix by the look of it

**Comment by gdams** [comment]
yeah the manifest job hasn't completed yet

**Comment by gdams** [comment]
@sxa latest has now been updated

**Pull request merged**
