### PR TITLE
aixPB: individual bootjdk roles replaced by generic role.

### PR DESCRIPTION
**Pull request by aixtools**
Only the bootjdk7 role remains separate - as it has vendor files.
- This cleans up the clutter by removing the individual role directories

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Review by karianna — CHANGES_REQUESTED** [review]
I don't see the generic role added?

**Comment by sxa** [comment]
> I don't see the generic role added?

@karianna See my referenced PR above - (Maybe the commit message should be clarified to say "Remove obsoleted individual bootjdkXX roles" or similar?

**Review by karianna — APPROVED** [review]

**Comment by aixtools** [comment]
commit message updated.

**Comment by sxa** [comment]
Out of release cycle so happy to merge this. The deleted roles are not used any more.

**Pull request merged**
