### PR TITLE
unixPb: Remove hyphen from Bootjdk symlinks

### PR DESCRIPTION
**Pull request by Haroon-Khel**
- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

ref https://github.com/adoptium/infrastructure/issues/2912

In light of https://github.com/adoptium/infrastructure/issues/2912#issuecomment-2399887738, this pr should not be merged while we have an upcoming release. And I will test the difference that this pr makes to the symlinks in our build containers by running builds in those containers

### CODE REVIEW

**Comment by Haroon-Khel** [comment]
Ive removed the hyphen from the windows symlinks

**Comment by Haroon-Khel** [comment]
Solaris has one bootjdk, /opt/csw/java/jdk1.7.0_80, so I dont think any change is required there. On AIX we use a different format, `/usr/java{{ jdk }}_64`, so at the moment I am not going to change that. Only linux, windows and mac have been updated

**Comment by Haroon-Khel** [comment]
Changes to the build scripts is here https://github.com/adoptium/temurin-build/pull/3992/files

**Comment by Haroon-Khel** [comment]
vpc https://ci.adoptium.net/job/VagrantPlaybookCheck/1984/console

**Comment by Haroon-Khel** [comment]
Latest vpc, without windows as that passed in the last one
https://ci.adoptium.net/job/VagrantPlaybookCheck/1988/console

**Comment by Haroon-Khel** [comment]
Latest vpc, https://ci.adoptium.net/job/VagrantPlaybookCheck/1995/console. Successes on the boxes it could connect to

**Review by karianna — APPROVED** [review]

**Comment by Haroon-Khel** [comment]
Without the hyphens in the symlinks the upstream configure is able to find the bootjdks without a problem, see https://github.com/adoptium/infrastructure/issues/2912#issuecomment-2435792702

**Review by sxa — COMMENTED** [review]
Initial comment - we can hopefully remove a lot of these definitions in the dockerfiles (and elsewhere) since we are now using the default locations expected by the openjdk build process which means we don't have to have them explicitly specified. Having said that I could be  ok with leaving them in for now and removing them in a future date

**Review by sxa — COMMENTED** [review]
Noting also that we have 50 machines in jenkins that have at least one `_BOOT_DIR` variable defined on them. Hopefully they can get cleared up too with these changes being made :-)

**Comment by Haroon-Khel** [comment]
Im going to hold off on the windows changes. It looks like the upstream configure looks in [C:\Program Files\Java//cygdrive/c/Program Files/Java](https://github.com/openjdk/jdk/blob/c33a8f52b613e5eff02f572eda876cbbfc7c22cf/make/autoconf/boot-jdk.m4#L273) which is where we already unpack the JDK on our machines
https://github.com/adoptium/infrastructure/blob/822366e945b4ef1f540aca9a29180f7999cf6026/ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java_install/tasks/main.yml#L37 and https://github.com/adoptium/infrastructure/blob/822366e945b4ef1f540aca9a29180f7999cf6026/ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Java8/tasks/main.yml#L27

**Comment by sxa** [comment]
> Im going to hold off on the windows changes. It looks like the upstream configure looks in [C:\Program Files\Java/ (/cygdrive/c/Program Files/Java)](https://github.com/openjdk/jdk/blob/c33a8f52b613e5eff02f572eda876cbbfc7c22cf/make/autoconf/boot-jdk.m4#L273) which is where we already unpack the JDK on our machines

Confirmed that it does indeed "just work" with our current setup 👍🏻

**Comment by Haroon-Khel** [comment]
>Noting also that we have 50 machines in jenkins that have at least one _BOOT_DIR variable defined on them. Hopefully they can get cleared up too with these changes being made :-)

Ive removed the BOOT_DIR variables from jenkins nodes (as much as I could if more are found please let me know)

**Review by sxa — APPROVED** [review]

**Pull request merged**
