### PR TITLE
unixPB: fix linter

### PR DESCRIPTION
**Pull request by sxa**
Fixes https://github.com/adoptium/infrastructure/issues/2906

Signed-off-by: Stewart X Addison <sxa@redhat.com>

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)

### CODE REVIEW

**Review by karianna — APPROVED** [review]

**Comment by karianna** [comment]
Checks pass - good to go?

**Comment by sxa** [comment]
> Checks pass - good to go?

Apparently so :-)

**Comment by sxa** [comment]
> Checks pass - good to go?

Apparently so :-)

**Review by Haroon-Khel — APPROVED** [review]
LGTM

**Pull request merged**
