### PR TITLE
Upgrade VS2022 Redist devkit to version vs2022_redist_14.40.33807_10.0.26100.1742

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
As part of moving to the latest VS2022 Redist UCRT DLLs: https://github.com/adoptium/temurin-build/issues/4086
Update Windows image to download: vs2022_redist_14.40.33807_10.0.26100.1742.zip

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [x] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
  - https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/2037/
- [ ] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Review by steelhead31 — APPROVED** [review]
Looks good.

**Comment by sxa** [comment]
Memo to self - backing up the original image with` docker tag win2022_notrhel_image win2022_notrhel_image_redist0` before rebuilding.

**Comment by sxa** [comment]
> I'll merge this and get it regenerated on the machines today before the next set of EA kick off

Testing at https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/windbld/1391/console - seems to have started the build without issues so I'm happy if that job goes green overall 👍🏻 
I'll get all of the other machines updated now.

**Comment by sxa** [comment]
All machines now updated, and the test job referenced in the previous comment has completed ok.
@andrew-m-leonard feel free to check that the artifacts on that build look ok to you.

**Pull request merged**
