### PR TITLE
inventory: Rename packet to equinix

### PR DESCRIPTION
**Pull request by sxa**
Packet rebranded itself to equinix last year. This change reflects that in our inventory
Resolves https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2045

Signed-off-by: Stewart X Addison <sxa@redhat.com>

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

Draft until dependent systems from the last checkbox above have been updated

### CODE REVIEW

**Review by gdams — APPROVED** [review]

**Review by karianna — APPROVED** [review]
LGTM - OK to take out of Draft?

**Comment by gdams** [comment]
ping @sxa I assume this is ready for merge?

**Comment by Haroon-Khel** [comment]
@sxa Is this ready for review?

**Comment by aixtools** [comment]
This seems silly - no action taken forever. What is the holdup?

**Comment by gdams** [comment]
@sxa I'm going to merge this now, it's a simple change that shouldn't require additional work. We've referred to the machines as Equinix ones for some time anyway

**Comment by sxa** [comment]
As per PR checkboxes, the rename had not occurred in the other servics which host it, so merging this makes the inventory inconsistent with how the hostname identifies itself and how it's referenced elsewhere in our infrastructure.

**Pull request merged**
