### PR TITLE
UnixPb: CentOS8 Updates

### PR DESCRIPTION
**Pull request by vsebe**
Use dnf config-manager to enable powertools repo.
Fix libdwarf package name.

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [x] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access) https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/1667/
- [ ] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM

**Comment by karianna** [comment]
Assume solaris failure is separate

**Comment by AdamBrousseau** [comment]
Bumping this so we can close it off on our end.

**Review by sxa — CHANGES_REQUESTED** [review]
Catching up with some old PRs. @vsebe Can you update the commit message to be more descriptive about what it's doing (e.g. "Fix libdwarf install on non-x64" or similar.

Also is the powertools a prereq for the libdwarf install or is the reason for that separate?

**Comment by vsebe** [comment]
Comment updated.
The powertools repo is a prereq for the libdwarf install on aarch64.

**Comment by sxa** [comment]
CentOS6 test failed but it may not be related to this PR so I'm re-running to see if it's repeatable.

**Comment by AdamBrousseau** [comment]
Bumping this to try and get it closed out. Thanks.

**Review by sxa — APPROVED** [review]

**Pull request merged**
