### PR TITLE
NagiosPB: Populate Nagios Server Config Files From j2.templates 

### LINKED ISSUE #2899: NagiosPB: Populate Nagios Server Config Files From j2.templates For Windows Machines
NagiosPB: Populate Nagios Server Config Files From j2.templates

Task 6.4.1 Of The Epic ( #2445 )

In an earlier part of the automation of nagios configuration, files with names similar to these

test-azure-win2012r2-x64-1.cfg  
build-ibmcloud-win2012r2-x64-2.cfg

were created as a place holder to be used for populating the config files appropriately

Starting off with Windows on this issue, write ansible code and any supporting scripts to populate the content of these files appropriately. This can be done using jinja2 templates , such as the example ones provided

test-windows-template.j2  
build-windows-template.j2

The logic should run along the lines of, if a host is a test & windows machine, its configuration should use the test-windows-template.j2 to populate its configuration file.

Thought should be given to how this mapping between service types, and machine description should be performed, in order to simplify the expansion. As this task will expand to cover all other service and host types.

### PR DESCRIPTION
**Pull request by lumuchris256**
Populated Nagios Server Config Files From j2.templates
 written ansible  and modified the .py script to populate the content of the server config files appropriately using jinja2 templates ,
 for all  services and host types, futher work is on the host types with special configs 

fixes #2899 
Signed off by ; @lumuchris256 
cc @steelhead31 @Haroon-Khel  @smlambert

### CODE REVIEW

**Comment by steelhead31** [comment]
I've just run the config_nagios playbook to test this PR, and the server templates are not being populated, please can you have a look at this... the xxxx.cfg files still have the dummy content "Configuration for build-alibaba-ubuntu1804-armv8-1"

**Review by steelhead31 — CHANGES_REQUESTED** [review]
Having tested the config\_server playbook, it is not populating the xxxxx.cfg files, please can you test/investigate within a vagrant machine, ( create vagrant machine, run create\_server playbook, then run config\_server playbook ) and check the output.

**Comment by lumuchris256** [comment]
> Having tested the config_server playbook, it is not populating the xxxxx.cfg files, please can you test/investigate within a vagrant machine, ( create vagrant machine, run create_server playbook, then run config_server playbook ) and check the output.

for some reason i might not have checked well the output destination logic

**Comment by lumuchris256** [comment]
> Having tested the config_server playbook, it is not populating the xxxxx.cfg files, please can you test/investigate within a vagrant machine, ( create vagrant machine, run create_server playbook, then run config_server playbook ) and check the output.

noted

**Comment by steelhead31** [comment]
The content of this has been merged into PR https://github.com/adoptium/infrastructure/pull/2948 , so Im closing this one as a duplicate.

**Pull request closed without merging**
