### PR TITLE
ansible: Change ownership of jenkins' ~/.ssh/known_hosts

### PR DESCRIPTION
**Pull request by fredg02**
Signed-off-by: Frederic Gurr <frederic.gurr@eclipse-foundation.org>

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Review by gdams — APPROVED** [review]

**Comment by sxa** [comment]
Before this is merged can you clarify what permissions it has if you don't do this? i.e. what's the description of the problem we're fixing?

**Review by sxa — CHANGES_REQUESTED** [review]
Before this is merged can you clarify what permissions it has if you don't do this? i.e. what's the description of the problem we're fixing?

**Comment by fredg02** [comment]
If we don't do this, the known_hosts file is owned by the root user and new host keys can't be added by the jenkins user.

**Review by sxa — APPROVED** [review]
Gotcha - it was an issue introduced after we started creating the known hosts file in https://github.com/adoptium/infrastructure/commit/938e83ace80776ac81a790ad55b40dd4369ab9b6

**Pull request merged**
