### PR TITLE
unixPB: Remove xorg packages to avoid dragging in gdm

### PR DESCRIPTION
**Pull request by sxa**
Signed-off-by: Stewart X Addison <sxa@redhat.com>

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [x] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access) [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/1344/)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

Please put the name of the software product (and affected platforms if relevant) in the title of this issue

The Adoptium AQAvit tests require `Xvfb` to be started on Linux in order to test GUI capabilities. Our playbooks currently install both Xvfb and Xorg - the latter of which shouldn't be necessary since the machines themselves are all either virtual or sitting in data centres, so I believe we can remove it (Perhaps it predates Xvfb?). On some Linux distributions (Certainly Ubuntu, possibly others) the `xorg` package, when installed via ansible, pulls in `gdm3` which results in it starting a GUI greeter on the "console" of the machine, chewin up resources unnecesarily.

ALTERNATE OPTION: We could continue to let it be installed, but ensure the greeter service is disabled on startup, although I'd rather not force that on everyone in case the playbooks are being run on people's desktop systems :-)

I've already mentioned this to @smlambert in the #testing channel but it would be good to hear from @AdamBrousseau to understand if he sees any problem with removing these packages.

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
If it's a test package and it is confirmed and tested that it isn't needed then I'm fine to have it removed. Thanks for the heads up.

**Comment by sxa** [comment]
1383 is also green, so this should ben good to merge when approved.

**Review by karianna — APPROVED** [review]
LGTM, I assume this doesn't harm TCK manual testing?

Solaris failure is unrelated!

**Comment by sxa** [comment]
> LGTM, I assume this doesn't harm TCK manual testing?

TCKs do not directly use these playbooks, but it should be safe there if if it was :-) Xvfb and VNC are the ones that are important there.

**Comment by aixtools** [comment]
If it is good to go - what are you waiting for? "Lean is Mean" (aka better)

**Pull request merged**
