### PR TITLE
aixPB: update RBAC role to include priv needed for core dumps

### PR DESCRIPTION
**Pull request by aixtools**
Fix: #1918 
##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md#commit-messages)
- [ ] [FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate
- [x] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Comment by Haroon-Khel** [comment]
Testing on ojdk06

**Review by Haroon-Khel — COMMENTED** [review]
Despite this change, I still get a dump error when running the testDDRExt_General_0 test

```
     [exec] addTestJitHint adding hint to java/lang/Thread$State.values
     [exec] JVMDUMP034I User requested System dump using '/home/jenkins/openjdk-tests/TKG/../TKG/output_16165189377817/testDDRExt_General_0/DDREXT.J9CORE.DMP' through com.ibm.jvm.Dump.SystemDump
     [exec] JVMDUMP012E Error in System dump: cannot find core file: "A file or directory in the path name does not exist.". check "ulimit -Hc" is set high enough
```

Disabling the rtclk role for the jenkins user did allow this test to pass

**Comment by aixtools** [comment]
Probably yet another PRIV needed. There is a reason people have found RBAC tough to implement. Lack of documentation re: what PV unlocks what (or locks by side-effect) is itterating.

If you can help out with a test I can run stand-alone (eg, with a save workspace) I can run tracepriv to see what are being used.

**Comment by Haroon-Khel** [comment]
ref https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1918#issuecomment-802985284

@sxa's testing of the pr

**Comment by aixtools** [comment]
re: #1918 - the AIX 7.2 they are testing on is AIX 7.2 TL5 SP1 - which is the 'latest' version of AIX - and not likely (yet) to be the version most businesses are running.

Are we still committed to supporting AIX 7.1 TL4 SP4 (or earlier) and later AIX systems - OR - do we need to update the AIX systems to a later 'base' level.

**Comment by sxa** [comment]
> Are we still committed to supporting AIX 7.1 TL4 SP4 (or earlier) and later AIX systems - OR - do we need to update the AIX systems to a later 'base' level.

That seems like something separate to this issue, unless upgrading the SP is likely to make a difference to the solution. Do you think it would?

**Comment by sxa** [comment]
What is the current situation on this - do we need to make further changes or are we confident that the set of tests which generate core dumps are ok with what's here?

**Comment by aixtools** [comment]
We never really tested this. Instead we have hacked away at jenkins user settings.

Depending on the `capabilities` setting will always be dependent on AIX os-level, and there is no documentation (easily available).

**Comment by sxa** [comment]
> Depending on the `capabilities` setting will always be dependent on AIX os-level, and there is no documentation (easily available).

Sounds like an opportunity to be trailblazers and put some docs in place (or even feedback to IBM if they want a blog post from us on our findings!)

**Comment by aixtools** [comment]
As this PR has conflicts - closing it and deleting this branch. I'll open a new PR with a new current patch.

**Pull request closed without merging**
