### PR TITLE
docker: Assign port number to static docker container during automated deployment

### PR DESCRIPTION
**Pull request by Haroon-Khel**
- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [x] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

fixes https://github.com/adoptium/infrastructure/issues/3505

### CODE REVIEW

**Review by steelhead31 — APPROVED** [review]
lgtm

**Comment by Haroon-Khel** [comment]
Tested this on dockerhost-azure-ubuntu2204-x64-1, works as expected

**Review by sxa — APPROVED** [review]
I'll approve but food for thought - would this work with `podman`?

**Review by karianna — APPROVED** [review]

**Comment by Haroon-Khel** [comment]
> would this work with podman?

I am not sure. I didnt think any of our machines were using podman?

**Pull request merged**
