### PR TITLE
unixPB: Install capstone 4 from repositories or source

### PR DESCRIPTION
**Pull request by sxa**
##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [x] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)  https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/1696

This is the machine setup part of [#hsdis](https://github.com/adoptium/adoptium/issues/213)

### CODE REVIEW

**Review by karianna — APPROVED** [review]

**Comment by sxa** [comment]
Moving back to draft until I put the changes in to restrict build by architecture to reduce library size. Also awaiting on merge of https://github.com/adoptium/infrastructure/pull/3120 which is preventing the VPC checks from passing.

**Comment by sxa** [comment]
Updated to only build one platform for each build to reduce library size.

Rebasing on top of maven signature PR which has now been merged: https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/1692/

**Comment by sxa** [comment]
Need to consider whether using the default compiler on each machine is sensible given that this is a library which will be reshipped...

**Comment by sxa** [comment]
Latest VPC run (linked in the description) looks like it has run through without problems related to this PR.

**Comment by sxa** [comment]
Converting back to draft due to consideration of having a pre-built versions stored on our servers that is downloaded during the build process in order to ensure reproducibility.

**Comment by sxa** [comment]
Testing along with the [corresponding build script changes](https://github.com/adoptium/temurin-build/pull/3414) in [VPC 1729](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/1729)

**Comment by sxa** [comment]
Re-running with the updates + rebase of the infrastructure PR, and updates to the build PR to move all the selection logic into `linux.sh`: https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/1730/

**Comment by sxa** [comment]
Noting that this is not in the DockerStatic role but since there are no tests requiring this yet that is not a requirement.

**Review by steelhead31 — APPROVED** [review]
LGTM

**Comment by sxa** [comment]
> Re-running with the updates + rebase of the infrastructure PR, and updates to the build PR to move all the selection logic into `linux.sh`: https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/1730/

Slightly concerned by the test case failures showing here, but that was are using the main development branch of JDK22 so i don't think it's related ...

running https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/1731 with JDK21.

**Comment by karianna** [comment]
> https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/1731

Failed sadly.

**Comment by sxa** [comment]
> > https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/1731

> Failed sadly.

Looks like ti was due to a bunch of hung processes causing the failures (Except the ones that were showing a yellow warning status which were due to the MBCS tests failing - suspect we'll need to look at that separately since the test may no longer be valid for JDK21+ ...

New run after clearing processes ir running better: https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/1732/

**Comment by sxa** [comment]
1732 mostly worked other than Solaris 10 which had an issue downloading the Liberica JDK11.
The yellow warning triangles are due to an issue with the MBCS tests on later versions of the JDK which I will raise another issue to investigate.

**Pull request merged**
