### PR TITLE
UnixPb: Install Cronie and Bzip2 for SLES

### PR DESCRIPTION
**Pull request by Haroon-Khel**
- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

Cronie is needed for crontab tasks. 
Without bzip2, the [expat](https://github.com/adoptium/infrastructure/blob/7c29bb812d58c4df12cfa2dad1779f9f2c724fe8/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/SLES.yml#L240) tarball will not extract

### CODE REVIEW

**Review by karianna — CHANGES_REQUESTED** [review]
Can you add comments as to why?

**Comment by zdtsw** [comment]
it is strange, the expat task in SLES.yml has been there for years, if it could not extract by missing bzip2, how it worked before.
do you have an issue or failed test/run that can be referred to?

**Comment by Haroon-Khel** [comment]
```
TASK [Common : Extract expat] **************************************************
fatal: [test-marist-sles12-s390x-2]: FAILED! => {"changed": false, "msg": "Failed to find handler for \"/tmp/expat-2.2.5.tar.bz2\". Make sure the required command to extract the file is installed. Command \"/bin/tar\" could not handle archive. Command \"/usr/bin/unzip\" could not handle archive."}
```
> it is strange, the expat task in SLES.yml has been there for years, if it could not extract by missing bzip2, how it worked before.

Perhaps some systems come with it installed. But it is still best to ensure it gets installed

```
TASK [Crontab : Add cron job to apply OS updates on zypper-based systems] ******
fatal: [test-marist-sles12-s390x-2]: FAILED! => {"changed": false, "msg": "Failed to find required executable \"crontab\" in paths: /opt/csw/bin/:/usr/local/bin:/opt/homebrew/bin:/sbin:/usr/sbin:/usr/local/sbin:/root/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games"}
```
Same with `cronie`

**Comment by Haroon-Khel** [comment]
The linter errors are due to the workflow using the latest version of the linter, as @zdtsw [commented](https://github.com/adoptium/infrastructure/pull/2707#issuecomment-1227088298)

I think resolving the linter issue should be done in a different issue/pr

**Comment by zdtsw** [comment]
is this found when you upgrade from sles12 sp3 to sp5?

**Comment by Haroon-Khel** [comment]
> is this found when you upgrade from sles12 sp3 to sp5?

I found it when I was setting up test-marist-sles12-s390x-2, sles12 sp5

**Comment by steelhead31** [comment]
> is this found when you upgrade from sles12 sp3 to sp5?
> 
> wonder if it relates to vules found in Cronie and Bzip2. i dont mind adding these two, as long as it does not introduce new security concern @steelhead31 how you feel?

Im happy for both of these to be installed on sles12 sp5, had to install cronie on sles15 also, the current version installed via zypper. AFAIK, the known vulnerabilities in both have largely been fixed, or are negligible as they already require someone to have privileged access to the machine.

**Review by zdtsw — APPROVED** [review]

**Comment by Haroon-Khel** [comment]
ping @karianna for rereview

**Review by sxa — APPROVED** [review]

**Review by karianna — APPROVED** [review]

**Pull request merged**
