### PR TITLE
UnixPB: Use 'changed_when: false' when using shell tasks to query

### PR DESCRIPTION
**Pull request by Willsparker**
Ref: #2424 
Fixes: #2422 

Going through the Windows and Unix playbooks, whenever a `shell` module has been used to query something, this hasn't technically changed anything on the machine, however the task will report `changed`. This is incorrect, so I've gone through and whenever I've found an instance of this, I added the `changed_when: false` option. 

Technically, we should avoid using the `shell` module, as we could use `stat` in most instances, however for the time being, this is a good compromise. 

**Note:** While I can test the UnixPB with VPC (see below), Windows is currently broken on it; so the changes to those files will require _(shudder)_ manual reviewing.

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [x] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access) [VPC-1390](https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1390/)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Review by sxa — COMMENTED** [review]
Hmmm I'm not really comfortable with stacking up Windows playbook changes that we can't test at the moment, so can we split them out into a separate PR for now until we have #2178 resolved? Also have you considered having an option to VPC that says "Run the playbook twice"?

**Comment by Willsparker** [comment]
PR's have been split :+1:

**Comment by Willsparker** [comment]
VPC passed! :partying_face:

**Review by aixtools — CHANGES_REQUESTED** [review]
I am not going to take a specific example, but instead mention that _blanket_ changes of adding `changed_when: false` disable ansible state checking.

There are times where you know this is true - and it is acceptable (imho), just as I consider `ignore_errors: true` to be acceptable in some situations.

But to just paste it into a task to get rid of a false changed: status to get rid of the changed status is dangerous, and I would be surprised in yamllint doesn't come up with an objection to it (just as it has to ignore_errors: true).

Wherever possible use a condition that can be resolved. Or, if you come across that you are sure CAN be better, mark a task with a comment saying it needs work (# TBD: develop conditional for changed_when, or # rewrite module to use ansible module xxx: (e.g., as your PR description mention, stat:).

Examples (from AIX playbooks): wrong ansible mode/options used): 
```
# TBD: touch should be replaced by file:, stat: present, rather than touch)
./roles/syslogs/tasks/main.yml:
- name: Ensure log files exist
  file:
    path: "{{ item }}"
    state: touch
    mode: 0644
  with_items:
    - /var/log/syslog
    - /var/adm/messages
    - /var/log/messages
  changed_when: false
  tags: syslog
```
- Instead, review the command behavior and come up with proper changed_when: and failed_when: conditionals
```
# Using set -o pipefail -o to quiet AnsibleLint breaks execution on AIX
# Use skip_ansible_lint tag instead
- name: Remove conflicting packages before install yum
  shell: rpm -e --nodeps $(rpm -qa | grep -E "cloud-init|perl|openssl")
  register: _cleanup
  changed_when: "'no packages given for erase' not in _cleanup.stderr"
  failed_when: _cleanup.changed and _cleanup.rc != 0
  when: _yum.stat.islnk is not defined
  tags:
    - yum
    - rpm_remove
    # TODO: rpm used in place of yum or rpm_key module
    - skip_ansible_lint
```

**Comment by Willsparker** [comment]
I agree, that we should probably go through these and change the modules to something more sensible, rather than `shell`. The `shell` commands that I've added `changed_when` to, have only been tasks that query the system (I've been careful not to add it to shell commands that 'do something', such as in your 2nd example). In this instance, `changed_when: false` is technically always true because it isn't changing the system.  

I think going through all of these commands and changing them to a more sensible module falls under #2492 , and that this PR isn't necessarily meant for that, but more as an interim thing :-)

**Comment by aixtools** [comment]
> I agree, that we should probably go through these and change the modules to something more sensible, rather than `shell`. The `shell` commands that I've added `changed_when` to, have only been tasks that query the system (I've been careful not to add it to shell commands that 'do something', such as in your 2nd example). In this instance, `changed_when: false` is technically always true because it isn't changing the system.
> 
> I think going through all of these commands and changing them to a more sensible module falls under #2492 , and that this PR isn't necessarily meant for that, but more as an interim thing :-)

Actually, I have no problem with `changed_when: false`, just as I had no issue with `ignore_errors: true`. However, the people who design yamllint do have very strong opinions re: `ignore_errors: true`. I am only wishing to point out that an interim change - without a quick follow-up - may just bring about new issues.

If everyone can live with that - I am silent as well.

**Comment by sxa** [comment]
@Willsparker Apologies for not getting back to this - do you think you can resolve the conflicts on this one so we can try and get it in?

**Comment by Willsparker** [comment]
@sxa I'll put it on my to-do list tomorrow :-)

**Comment by Willsparker** [comment]
Merge conflict resolved :+1:

**Review by karianna — APPROVED** [review]
LGTM

**Comment by sxa** [comment]
Runnign through one final VPC before merging: https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1460/

**Comment by Willsparker** [comment]
@sxa Seems to have worked okay? :)

**Review by sxa — APPROVED** [review]

**Pull request merged**
