### PR TITLE
ansible: fix linter

### PR DESCRIPTION
**Pull request by zdtsw**
- vars list syntax: https://github.com/adoptium/infrastructure/actions/runs/2494052012
	- removed empty "when"
	- make 1 as string

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Comment by zdtsw** [comment]
@sxa @steelhead31 can I get a review on this one?

**Review by steelhead31 — APPROVED** [review]
All looks good to me.

**Review by sxa — COMMENTED** [review]
Just one comment - other than that I'll be glad to see the linter errors cleared up

**Review by sxa — APPROVED** [review]
LGTM

**Comment by sxa** [comment]
Running VPC check at https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1467/

**Review by karianna — APPROVED** [review]
LGTM

**Comment by sxa** [comment]
> Running VPC check at https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1467/

Failures were due to the presence of `/` in the branch name, not the changes themselves. Merging.

**Pull request merged**
