### PR TITLE
ansible: fix certain lint

### PR DESCRIPTION
**Pull request by zdtsw**
update: 
1. use docker_container module instead of command to start/restart container
2. change ignore_errors to failed_when for lint issue

- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [x] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Review by karianna — CHANGES_REQUESTED** [review]
Although not the same linter as we apply, the GitHub beta linter also flags a number of cases:

`ignore-errors Use failed_when and specify error conditions instead of using ignore_errors.`

**Comment by zdtsw** [comment]
> Although not the same linter as we apply, the GitHub beta linter also flags a number of cases:
> 
> `ignore-errors Use failed_when and specify error conditions instead of using ignore_errors.`

another commit, changed all files with such linter warning

**Review by karianna — APPROVED** [review]
LGTM

**Comment by zdtsw** [comment]
@sxa Could I have a review and get this one merged? Failing vagrant on Solairs is a known issue

**Comment by sxa** [comment]
@aixtools Can you take a look at this PR and confirm there shoujldn't be any issues with the changes to the AIX playbook conditionals in this please?

**Comment by sxa** [comment]
VPC running at https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/1420/

**Comment by zdtsw** [comment]
> VPC running at https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/1420/

not really sure about this result:
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Debian8,label=vagrant/1420/console
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Solaris10,label=vagrant/1420/console
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Debian10,label=vagrant/1420/console
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Ubuntu2104,label=vagrant/1420/console
**dont see anything wrong, but marked as failed**
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Win2012,label=vagrant/ **never had a green build**
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Ubuntu2004,label=vagrant/1420/console `{"msg": "Failed to connect to the host via ssh: ssh: connect to host 127.0.0.1 port 2200: Connection refused"}`
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Fedora35,label=vagrant/
**no f35 for vagant job need to re-config**
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=CentOS7,label=vagrant/1420/console 
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=CentOS8,label=vagrant/1420/console
`adoptopenjdkC7: Warning: Authentication failure. Retrying.`
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Ubuntu1604,label=vagrant/1420/console 
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Ubuntu1804,label=vagrant/1420/console
`Failed to connect to the host via ssh: Shared connection to 127.0.0.1 closed."`

**Comment by zdtsw** [comment]
@Willsparker can I have review on this PR?

**Review by Willsparker — APPROVED** [review]
LGTM

**Pull request merged**
