### PR TITLE
Dockerstatic: Add packages for uptime, diff and hostname for UBI8

### PR DESCRIPTION
**Pull request by Haroon-Khel**
- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

ref https://github.com/adoptium/infrastructure/issues/2882#issuecomment-1385769644

These packages are needed on ubi8 for jdk_management tests to pass, see https://github.com/adoptium/infrastructure/issues/2882#issuecomment-1384516670

### CODE REVIEW

**Comment by Haroon-Khel** [comment]
Im in favour of replacing the ubuntu21 dockerstatic pr check for ubuntu22 as it is more up to date, and we have to ubuntu21 x64 static docker containers in jenkins. Any objections?

**Comment by sxa** [comment]
> Im in favour of replacing the ubuntu21 dockerstatic pr check for ubuntu22 as it is more up to date, and we have to ubuntu21 x64 static docker containers in jenkins. Any objections?

Does that have anything to do with this PR?

**Review by sxa — APPROVED** [review]

**Review by steelhead31 — APPROVED** [review]
LGTM!

**Comment by Haroon-Khel** [comment]
@sxa No, I just thought it may need updating

**Pull request merged**
