### PR TITLE
unixPB: upgrade nodejs from 12.x to 16.x for TRSS

### PR DESCRIPTION
**Pull request by zdtsw**
Fixes: https://github.com/adoptium/infrastructure/issues/2591
##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Comment by zdtsw** [comment]
@Haroon-Khel Could you run https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/ for me? most important on ubuntu18

**Comment by zdtsw** [comment]
> The VagrantPlaybookCheck job will test only the `main.yml` playbook, not the `trss.yml` one

ah, ok, good to know!
any other way i can test it, except i start a local docker container and run ansible against it?

**Comment by Haroon-Khel** [comment]
> ah, ok, good to know!
any other way i can test it, except i start a local docker container and run ansible against it?

That's a fine way to test it

**Review by karianna — APPROVED** [review]
LGTM

**Pull request merged**
