### PR TITLE
aixPb: Put /usr/bin in front of PATH

### PR DESCRIPTION
**Pull request by Haroon-Khel**
- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [x] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

To escape the rebase hell that is https://github.com/adoptium/infrastructure/pull/2288/, ive simply created a new pr :)

### CODE REVIEW

**Review by sxa — COMMENTED** [review]
Why is `/etc` in there? I can't think of anything we need in the PATH that would be in there

**Comment by Haroon-Khel** [comment]
Not sure. I'll remove it

**Review by steelhead31 — APPROVED** [review]
Looks ok.

**Review by sxa — APPROVED** [review]

**Review by sxa — APPROVED** [review]
We should also bear in mind that while this will be ok for new machines it likely won't change the existing machines which have `PATH=/opt/freeware/bin` at the start as [most machines currently won't match this regex](https://github.com/adoptium/infrastructure/pull/2288#pullrequestreview-847554635), so if we don't put another case in here for that we'll need to look at patching the existing machines up (as described in https://github.com/adoptium/infrastructure/pull/2288#issuecomment-1008679917). Also noting that this regex to update the config will trigger on every playbook execution since it sets the path to something that has `PATH=/usr/bin` at the start. Something like @aixtools' proposal in https://github.com/adoptium/infrastructure/pull/2288#pullrequestreview-771855793 may be preferable, but I'm also ok with a one-off manual fixup.

**Comment by karianna** [comment]
> We should also bear in mind that while this will be ok for new machines it likely won't change the existing machines which have `PATH=/opt/freeware/bin` at the start as [most machines currently won't match this regex](https://github.com/adoptium/infrastructure/pull/2288#pullrequestreview-847554635), so if we don't put another case in here for that we'll need to look at patching the existing machines up (as described in [#2288 (comment)](https://github.com/adoptium/infrastructure/pull/2288#issuecomment-1008679917)). Also noting that this regex to update the config will trigger on every playbook execution since it sets the path to something that has `PATH=/usr/bin` at the start. Something like @aixtools' proposal in [#2288 (review)](https://github.com/adoptium/infrastructure/pull/2288#pullrequestreview-771855793) may be preferable, but I'm also ok with a one-off manual fixup.

holding off merging until we raise any appropriate work items here for consistency.

**Review by gdams — APPROVED** [review]

**Comment by Haroon-Khel** [comment]
I've manually updated the PATH on the current machines to start with `/usr/bin:/opt/IBM/xlC/13.1.3/bin:/opt/freeware/bin:`

**Comment by aixtools** [comment]
And, are there issues after this manual change? Thought I'd give it a bit of rest.

**Pull request merged**
