### PR TITLE
ansible: Install shared-mime-info on Centos UBI RHEL and Fedora

### PR DESCRIPTION
**Pull request by Haroon-Khel**
- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

ref https://github.com/adoptium/infrastructure/issues/3614#issuecomment-2211131526 shared-mime-info is needed for java/nio/file/Files/probeContentType/Basic.java to pass

### CODE REVIEW

**Review by sxa — COMMENTED** [review]
Can you run this through VPC before we approve please?

**Comment by Haroon-Khel** [comment]
VPC running on Centos6 7 and 8

https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/1908/console

**Comment by sxa** [comment]
> VPC running on Centos6 7 and 8
> 
> https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/1908/console

Not Fedora?

**Comment by Haroon-Khel** [comment]
> Not Fedora?

I must have missed it https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/1909/

On that note, F35 is EOL. I've created https://github.com/adoptium/infrastructure/issues/3662 to have it upgraded

**Comment by Haroon-Khel** [comment]
The playbooks ran fine in each of the vpc except for centos6 https://ci.adoptium.net/job/VagrantPlaybookCheck/OS=CentOS6,label=vagrant/1908/console but the failure is not related to the playbook execution

**Review by sxa — APPROVED** [review]

**Review by steelhead31 — APPROVED** [review]
Looks good.

**Pull request merged**
