### PR TITLE
docs: Add Infrastructure Providers logos

### PR DESCRIPTION
**Pull request by gdams**
##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Review by Willsparker — APPROVED** [review]
LGTM

**Comment by karianna** [comment]
Is the PNG generated somehow?  It captures the logos, but it's um not very well spaced out :-)

**Review by andrew-m-leonard — APPROVED** [review]

**Comment by sxa** [comment]
> Is the PNG generated somehow? It captures the logos, but it's um not very well spaced out :-)

A question for @gdams

**Comment by sxa** [comment]
@karianna No answer yet on your question but do you consider that a blocker?

**Pull request merged**
