### PR TITLE
aixPB: remote 'set -o pipefail' as lint measure (yum role)

### PR DESCRIPTION
**Pull request by aixtools**
update task code for accurate ansible reporting on changed: or ok:
 Rewrite comments so they better fit with 80 character line length.

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Review by sxa — COMMENTED** [review]
Changes look ok, but was the commit message supposed to say `remove` rather than `remote`?

**Comment by aixtools** [comment]
yes, remove "set -o pipefail" as that was the text that was initially used to get the yamllint to pass. But since the option pipefail is not supported by ksh - nothing ever ran after the lint correction was made. :wink:

**Review by sej-jackson — COMMENTED** [review]
I'm happy with the changes themselves, but also wondering if the `remote`/`remove` typo in the commit statement needs addressing before the merge, or is the conversation with sxa sufficient to deal with any potential confusion?

**Comment by sxa** [comment]
> I'm happy with the changes themselves, but also wondering if the `remote`/`remove` typo in the commit statement needs addressing before the merge, or is the conversation with sxa sufficient to deal with any potential confusion?

Needs to be fixed, ideally by the PR originator, although I can also override it when merging :-)

**Comment by aixtools** [comment]
I'll fix, and merge the lintfix into one, and force push.

**Review by sxa — APPROVED** [review]
Thanks For future reference, `git rebase -i HEAD~2` would probably have let you do it in one.

**Pull request merged**
