### PR TITLE
Update Win playbook to OpenSSL 1.1.1m

### PR DESCRIPTION
**Pull request by AdamBrousseau**
eclipse-openj9/openj9#14208

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

##### Checklist

- [ ] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM

**Comment by sxa** [comment]
@Haroon-Khel Can you handle deploying this on the build machines please?

**Comment by Haroon-Khel** [comment]
Already on it 👍🏻

**Comment by Haroon-Khel** [comment]
Ive deployed this onto all of the windows build machines

**Comment by sxa** [comment]
> Ive deployed this onto all of the windows build machines

In which case you should take the glory from merging this PR now :-)

**Pull request merged**
