### PR TITLE
UnixPB: Remove Nagios Tunnel Scripts For Improved Security

### LINKED ISSUE #3524: ToB13 - Nagios Reverse Tunneling Scripts
Fix the issue detailed in the trail of bits audit, re:

SSH clients maintain a list of known-good hosts they have connected to before. Host key verification is then used to prevent man-in-the-middle (MitM) attacks. The current method using a reverse tunnel to create the nagios configuration file, is insecure.

Following the security audit, the reverse tunnel scripts were deemed to be a security risk, vulnerable to man in the middle attacks. The creation of the nagios server specific config files, has already been migrated to the Nagios\_Config playbook, and a new issue has been created for a new / amended playbook to configure the ssh connection. ( See #3525 )

### PR DESCRIPTION
**Pull request by steelhead31**
Fixes #3524 

Following the security audit, the reverse tunnel scripts were deemed to be a security risk, vulnerable to man in the middle attacks. The creation of the nagios server specific config files, has already been migrated to the Nagios_Config playbook, and a new issue has been created for a new / amended playbook to configure the ssh connection. ( See https://github.com/adoptium/infrastructure/issues/3525 )

This PR removes the 2 problematic roles, from the playbook.

##### Checklist

- [X] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)

### CODE REVIEW

**Comment by steelhead31** [comment]
VPC in progress: https://ci.adoptium.net/job/VagrantPlaybookCheck/1868/

**Review by gdams — APPROVED** [review]

**Review by karianna — APPROVED** [review]

**Review by sxa — APPROVED** [review]

**Pull request merged**
