### PR TITLE
WindowsPB: Include Checksum Verification of VS2019 Layout

### LINKED ISSUE #3166: WindowsPB: Add Checksum Verification For VS2019 layout
WindowsPB: Add Checksum Verification For VS2019 layout

### PR DESCRIPTION
**Pull request by steelhead31**
Fixes #3166 

##### Checklist

- [X] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)

### CODE REVIEW

**Comment by steelhead31** [comment]
Runs ok on windows server 2022, VPC check in progress on https://ci.adoptium.net/job/VagrantPlaybookCheck/1707/

**Comment by steelhead31** [comment]
VPC looks good, moving to review ready.

**Comment by karianna** [comment]
@steelhead31 I assume the failed GH Action is the thing that'll get fixed by this?

**Comment by steelhead31** [comment]
> @steelhead31 I assume the failed GH Action is the thing that'll get fixed by this?

Im afraid not, the GitHub action relates to something to do with the DLL registration for VS2017, I can't replicate that issue to figure out how to fix it though...

**Comment by steelhead31** [comment]
@karianna I've picked up issue #3106 to try and see if I can find the underlying cause/solution to the Github Action failing.

**Review by gdams — APPROVED** [review]

**Review by Haroon-Khel — APPROVED** [review]

**Pull request merged**
