### PR TITLE
ansible: Decommissioning of old solaris/x64 systems

### PR DESCRIPTION
**Pull request by pstankie**
Removes jck-equinix_esxi-solaris10u11-x64-1, jck-equinix_esxi-solaris10u11-x64-2 EF issue #2428 https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2428

Signed-off-by: Pawel Stankiewicz <pawel.stankiewicz@eclipse-foundation.org>

##### Checklist

- [ x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)

### CODE REVIEW

**Review by gdams — APPROVED** [review]

**Review by karianna — APPROVED** [review]
LGTM

**Comment by fredg02** [comment]
Can this PR be merged?

**Review by gdams — APPROVED** [review]

**Pull request merged**
