### PR TITLE
AIXPB: add maxuproc to sys0 role

### PR DESCRIPTION
**Pull request by aixtools**
Fixes: https://github.com/adoptium/infrastructure/issues/3138
##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Review by sxa — APPROVED** [review]

**Review by karianna — APPROVED** [review]

**Comment by aixtools** [comment]
Is the freeze over?

**Comment by aixtools** [comment]
Again, is the freeze over? I was going to work further on some aixPB stuff, but don't want to have to be doing a lot of extra work because approved changes have not been merged yet. - i.e. I do not see my position to run the / thraw action. 

UNLESS someone else says okay.

**Comment by karianna** [comment]
Freeze is over as far as I'm aware.

**Pull request merged**
