### PR TITLE
winPB: Add 'changed_when: false' when using shell tasks to query

### PR DESCRIPTION
**Pull request by Willsparker**
Ref: #2422 , #2449

The same as #2449 , however this is specific to the Windows PB. 

This is currently blocked by #2178 , as we're unable to use VPC to test the changes.  

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Comment by sxa** [comment]
> This is currently blocked by https://github.com/adoptium/infrastructure/issues/2178 , as we're unable to use VPC to test the changes.

`FAST_MODE` switches off `MSVS_2010,VS2010_SP1,MSVS_2013` for JDK11+ so would bypass that problem. I've kicked off another VPC at https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/1440/ with that option

**Comment by Willsparker** [comment]
Rerunning as that one failed with a connection issue :)
https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/1459/

**Comment by sxa** [comment]
Hmmm perl download failed so trying Windows again at https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/1461

**Review by karianna — APPROVED** [review]
LGTM

**Review by sxa — APPROVED** [review]

**Pull request merged**
