### PR TITLE
VPC: Exclude sbom directory from TEST_JDK_HOME export for tests.

### PR DESCRIPTION
**Pull request by steelhead31**
Fixes issue #2617 

##### Checklist

- [X] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [x] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Comment by steelhead31** [comment]
VPC Run : https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/1472/

**Comment by sxa** [comment]
Looks like we had a debug printout of the directories in the line above just before filtering them - useful :-)

**Review by sxa — APPROVED** [review]
LGTM - I'm happy with this :-)

**Comment by steelhead31** [comment]
VPC run is completed

**Pull request merged**
