### PR TITLE
Gather CPU and Memory info across Linux, MacOS and Windows

### PR DESCRIPTION
**Pull request by neomatrix369**
A naive approach to gathering machine specs from the list in the [inventory.yaml](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/inventory.yml) file.

Happy to suggestions for improvements.

So far it does not work well on flavours of Linux other than Ubuntu, and cannot access Windows machines so can't say if the commands even work.

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
Somewhat related
https://github.com/AdoptOpenJDK/openjdk-jenkins-helper

**Comment by neomatrix369** [comment]
> Somewhat related
> https://github.com/AdoptOpenJDK/openjdk-jenkins-helper
> Although I don't believe it's currently in use.

I guess this is a simpler version, that we can quickly run and get the task done!

**Comment by karianna** [comment]
> Somewhat related
> https://github.com/AdoptOpenJDK/openjdk-jenkins-helper
> Although I don't believe it's currently in use.

I'm trying to remember but I think the jenkins-helper had some security concerns...

**Comment by karianna** [comment]
@johnoliver Needs a security review....

**Comment by AdamBrousseau** [comment]
I believe there were security warnings with pieces related to adding Jenkins nodes. Functionality requiring Jenkins admin level access.

**Comment by neomatrix369** [comment]
@johnoliver @karianna any update on this one?

**Comment by karianna** [comment]
@sxa Suspect this is superseded by Nagios, should we close?

**Comment by sxa** [comment]
> @sxa Suspect this is superseded by Nagios, should we close?

Yeah I think any of the requirements for this are probably covered by Nagios, so I'll close. It can be reopened if required.

**Pull request closed without merging**
