### PR TITLE
unixPb: Update Ant version to latest 1.10.15

### PR DESCRIPTION
**Pull request by Haroon-Khel**
- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

ref https://github.com/adoptium/infrastructure/issues/3074

To do:
- [x] Build each modified static container's dockerfile
- [x] Test playbook changes
- [x] Run AQA pipelines on affected static containers and machines

### CODE REVIEW

**Comment by Haroon-Khel** [comment]
VPC https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/1964/console

**Comment by Haroon-Khel** [comment]
Latest vpc https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/1965/console

**Comment by Haroon-Khel** [comment]
Ant updated on the following static docker machines

test-docker-amazon2023-x64-1 https://ci.adoptium.net/job/AQA_Test_Pipeline/355/console

test-docker-fedora41-x64-1 https://ci.adoptium.net/job/AQA_Test_Pipeline/356/console

test-docker-debian12-x64-4 https://ci.adoptium.net/job/AQA_Test_Pipeline/357/console

test-docker-ubuntu2404-x64-1 https://ci.adoptium.net/job/AQA_Test_Pipeline/358/console

test-docker-ubi9-x64-1 https://ci.adoptium.net/job/AQA_Test_Pipeline/359/console

test-docker-fedora41-armv8-1 https://ci.adoptium.net/job/AQA_Test_Pipeline/360/console

test-docker-ubuntu2404-armv8-1 https://ci.adoptium.net/job/AQA_Test_Pipeline/361/console

test-docker-sles12-s390x-1 https://ci.adoptium.net/job/AQA_Test_Pipeline/362/console

test-docker-sles15-s390x-1 https://ci.adoptium.net/job/AQA_Test_Pipeline/363/console

**Comment by Haroon-Khel** [comment]
Testing ant v1.10.15 on vms

test-azure-ubuntu2404-x64-1 https://ci.adoptium.net/job/AQA_Test_Pipeline/364/console

test-osuosl-ubuntu1604-ppc64le-1 https://ci.adoptium.net/job/AQA_Test_Pipeline/365/console

test-osuosl-ubuntu2404-aarch64-1 https://ci.adoptium.net/job/AQA_Test_Pipeline/367/console

test-marist-rhel8-s390x-2 https://ci.adoptium.net/job/AQA_Test_Pipeline/369/console

**Comment by Haroon-Khel** [comment]
Latest vpc https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/1966/console

**Review by karianna — APPROVED** [review]

**Comment by Haroon-Khel** [comment]
Results from test-azure-ubuntu2404-x64-1 https://ci.adoptium.net/job/AQA_Test_Pipeline/364/console

Various failures. Going to rerun them on the same machine to see if theyre related to the Ant upgrade. If they continue to fail then Ill try rerunning them on the same machine with a rolled back version of Ant to see if they still fail.

Rerun with Ant v1.10.15:
JDK 8
- Sanity rerun https://ci.adoptium.net/job/Grinder/11019/console
- Extended rerun https://ci.adoptium.net/job/Grinder/11017/console

JDK 11
- sanity rerun https://ci.adoptium.net/job/Grinder/11018/console
- extended rerun https://ci.adoptium.net/job/Grinder/11020/console

JDK 17
- sanity rerun https://ci.adoptium.net/job/Grinder/11021/console
- extended rerun
  - jdk_custom https://ci.adoptium.net/job/Grinder/11022/console
  - hotspot custom https://ci.adoptium.net/job/Grinder/11023/console

JDK 21
- sanity rerun https://ci.adoptium.net/job/Grinder/11024/console
- extended rerun
  - jdk_custom https://ci.adoptium.net/job/Grinder/11025/console
  - hotspot_custom https://ci.adoptium.net/job/Grinder/11026/console

**Comment by Haroon-Khel** [comment]
Since the test failures on test-azure-ubuntu2404-x64-1 are persistent with ant v1.10.15, I am going to roll back the version of ant and rerun the tests

Rerun with Ant **v1.10.5**:
JDK 8
- Sanity rerun https://ci.adoptium.net/job/Grinder/11031/console
- Extended rerun https://ci.adoptium.net/job/Grinder/11032/console

JDK 11
- sanity rerun https://ci.adoptium.net/job/Grinder/11033/console
- extended rerun https://ci.adoptium.net/job/Grinder/11034/console

JDK 17
- sanity rerun https://ci.adoptium.net/job/Grinder/11035/console
- extended rerun
  - jdk_custom https://ci.adoptium.net/job/Grinder/11036/console
  - hotspot custom https://ci.adoptium.net/job/Grinder/11037/console

JDK 21
- sanity rerun https://ci.adoptium.net/job/Grinder/11039/console
- extended rerun
  - jdk_custom https://ci.adoptium.net/job/Grinder/11040/console
  - hotspot_custom https://ci.adoptium.net/job/Grinder/11041/console

**Comment by Haroon-Khel** [comment]
Testing SBOM generation with Ant v1.10.15:

AIX build on build-osuosl-aix72-ppc64-2 https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-temurin/405/console

For our linux builds, I am running a JDK21 linux build in an adoptium/centos7 build container with an upgraded version of Ant

The windows machines are not idle at the moment, so I will test on them later

**Review by steelhead31 — APPROVED** [review]
looks good, approving on the basis its been tested :)

**Pull request merged**
