### PR TITLE
unixPB: Add strace tooling for Unix platforms, and truss for Solaris

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Fixes https://github.com/adoptium/infrastructure/issues/3251

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Review by steelhead31 — APPROVED** [review]
LGTM

**Review by karianna — APPROVED** [review]

**Review by Haroon-Khel — APPROVED** [review]

**Review by sxa — DISMISSED** [review]
I'm going to put a block on this to stop it being merged for now until we've checked it on a VPC run to stop any immediately obvious issues.

https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/1803

**Comment by sxa** [comment]
Also a question - is `truss` not on Solaris systems by default?

**Comment by andrew-m-leonard** [comment]
> Also a question - is `truss` not on Solaris systems by default?

@sxa I can't find any info that would confirm that?

**Comment by andrew-m-leonard** [comment]
The VPC would indicate a problem on Solaris:```
09:54:17 failed: [127.0.0.1] (item=truss) => {"ansible_loop_var": "item", "changed": false, "item": "truss", "msg": "Package truss not in catalog. Exiting.\n"}
```

**Comment by andrew-m-leonard** [comment]
VPC runs:
Debian10, Ubuntu1604:  https://ci.adoptium.net/job/VagrantPlaybookCheck/1802/

**Comment by sxa** [comment]
Hadn't seen that you'd done a VPC run on a couple of platforms yesterday, so that's good (Note for the future: please add the link to that in the description if possible so it's clear that it's been attempted - I should probably get that added into the PR template now).

Hopefully 1803 will show this PR as ok on the other Linux ones later today in which case I'll approve :-)

**Comment by sxa** [comment]
Noting that this being made live when it's merged will be gated on https://github.com/adoptium/infrastructure/pull/3263

**Review by sxa — APPROVED** [review]
Looks good based on the VPC runs

**Pull request merged**
