### PR TITLE
UnixPB: Add tags to tasks in Common role

### PR DESCRIPTION
**Pull request by aswinkr77**
Added tags to sub folder tasks in Common role, such that these tags can be used to run/skip the respective tasks.

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access) SXA: ~~Running https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/1875/~~ <<< Failed for a variety of reasons so I'm trying again at https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/1877/ <<< Also failed for various reasons - https://ci.adoptium.net/job/VagrantPlaybookCheck/1880/. New run 1/July https://ci.adoptium.net/job/VagrantPlaybookCheck/1898/ 4/Dec: https://ci.adoptium.net/job/VagrantPlaybookCheck/2034/
- [ ] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Comment by sxa** [comment]
I've started running the VPC checks (link in description)
This PR is in reference to the thread at https://adoptium.slack.com/archives/C53GHCXL4/p1716809812153839 where the user was unable to run the playbooks with `-t patch_update` to initiate that part of the `Common` role

**Comment by karianna** [comment]
@aswinkr77  Seems to be a number of CI failures, not sure if related...

**Comment by aswinkr77** [comment]
@karianna it's related I think. The task `- name: Perform OS setup and configuration` contains the `adoptopenjdk` tag which is used as the skip tag, so the task is getting skipped.

**Comment by aswinkr77** [comment]
I think I'll remove all the unnecessary tags and add only the necessary tags we need in the main.yml file.

**Comment by aswinkr77** [comment]
This solution is not viable at the moment. I'll add the missing tags to the tasks and stick with skipping tags instead of running the tags.

**Comment by aswinkr77** [comment]
@sxa I've changed the approach. Since the VPC checks were failing - related to the newly(previously) added tags in the main.yml file. Now I've removed it, and added tags to almost all tasks in all sub folder tasks in Common role. So these tags can be used to skip unnecessary tasks.

**Review by Haroon-Khel — APPROVED** [review]

**Comment by aswinkr77** [comment]
@sxa any updates in this?

**Comment by sxa** [comment]
> @sxa any updates in this?

Apologies for not being too responsive on this. What's making me nervous is whether it will definitely work in both situations i.e. will the playbooks run to completion with `--skip-tags build_tools` and also with `-t build_tools`. until these work I'm not sure what we're gaining with the changes.

As an example I've just tried a quick test on a few scenarios using --skip-tags build_tools:
- Alpine failed on the curl role
- Ubuntu 22.04 failed on the ant role (trying to do the GPG signature validation)
- CentOS7 failed in `Common : Set Default JRE (CentOS 7 and later)` with `'dict object' has no attribute 'lnk_source'`

With `-t build_tools` I get GPG signature failures when it gets to the the `cmake` role (e.g. on CentOS7 because `wget` is missing) and on Ubuntu 22.04 it fails when it gets to `gcc_7` because it doesn't have `xz` available. So overall I think there may be some work to be done to get this into a state where it would be usable.

A coupler of other notes:
- Can you rebase this PR please? (It currently won't work on CentOS7 at all unless you do that sine it went EOL at the end of last month)
- Semi-related: I was thinking of doing a separate PR that lets people skip the whole Common role. Mostly because when I'm testing changes it's quite nice to skip that role which can take a bit of time to run. So if you see me put in a PR for that it's completely separate from this work and will not supercede this one.

**Comment by karianna** [comment]
Have rebased via GH UI

**Comment by aswinkr77** [comment]
@sxa 
My first approach was to use tags to run tasks, for that to work, the tags from tasks should be present in the `main.yml` file of Common role(so that tags will be picked up by ansible). But when I tested that changes(my first PR was about it), the entire Common role was skipped because some of the tags used in the main.yml was used as skip tags, so all the vagrant failed. So I changed my approach.
Now I'm using tags to skip tasks to achieve the goal, so basically as of now only `--skip-tags` will work and not `-t`:
```
ansible-playbook -u root -i ~/aswin_list.txt --tags build_tools ibm_main.yml --ssh-common-args='-o StrictHostKeyChecking=no'

PLAY [all] *******************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************
ok: [ubuntu22-docker-test-1.fyre.ibm.com]

PLAY RECAP *******************************************************************************************************************************************************************************************************
ubuntu22-docker-test-1.fyre.ibm.com : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
the example shown here is using a customized play level ibm_main.yml file, somehow the main.yml is running all the roles, instead of running only the roles/tasks associated with the particular tags specified in `--tags`.

> With -t build_tools I get GPG signature failures when it gets to the the cmake role (e.g. on CentOS7 because wget is missing) and on Ubuntu 22.04 it fails when it gets to gcc_7 because it doesn't have xz available. So overall I think there may be some work to be done to get this into a state where it would be usable.

the `cmake` and `gcc_7` roles are not supposed to run when `-t build_tools` is used, since `cmake` and `gcc_7` uses `cmake` and `gcc_7` tags respectively. I'm not sure why it ran these roles.

The `--skip-tags` is working as expected:
```
ansible-playbook -u root -i ~/aswin_list.txt --skip-tags build_tools main.yml --ssh-common-args='-o StrictHostKeyChecking=no' --extra-vars='ansible_password=Ni4!ufbeQ7akcq@'

PLAY [Ansible Unix playbook] *************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************
ok: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : If ansible_processor_cpus is not defined, set to ansible_processor_cores or 1] ********************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Include OS variables] *****************************************************************************************************************************************************************************
ok: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Perform OS setup and configuration] ***************************************************************************************************************************************************************
included: /Users/aswin/Personal/Eclipse Adoptium/infrastructure/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Ubuntu.yml for ubuntu22-docker-test-1.fyre.ibm.com

TASK [Common : Install gnugp2 for S390x] *************************************************************************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Install gnupg2 for aarch64] ***********************************************************************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Add Azul Zulu GPG Package Signing Key for x86_64] *************************************************************************************************************************************************
changed: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Add Azul Zulu repository for x86_64] **************************************************************************************************************************************************************
changed: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Run apt-get upgrade] ******************************************************************************************************************************************************************************
changed: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Call Build Packages and Tools Task] ***************************************************************************************************************************************************************
included: /Users/aswin/Personal/Eclipse Adoptium/infrastructure/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/build_packages_and_tools.yml for ubuntu22-docker-test-1.fyre.ibm.com

TASK [Common : Set package manager var] **************************************************************************************************************************************************************************
ok: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Set package manager var for FreeBSD] **************************************************************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Install Test Tool Packages] ***********************************************************************************************************************************************************************
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=acl)
ok: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=perl)
ok: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=xauth)
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=xvfb)
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=binfmt-support)
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=qemu-user-static)
ok: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=unzip)
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libexpat1-dev)
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libcurl4-openssl-dev)
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=fakeroot)
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=jq)
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=gnutls-bin)
ok: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libnss3)
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libnss3-tools)
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libnss3-dev)

TASK [Common : Install additional Test Tool Packages for x86_64] *************************************************************************************************************************************************
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=pulseaudio)

TASK [Common : Install additional Packages specific to Ubuntu 16] ************************************************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libgstreamer0.10-dev)
skipping: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libgstreamer-plugins-base0.10-dev)
skipping: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libmpfr4)
skipping: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libmpfr4-dbg)
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Install additional Packages specific to Ubuntu 18] ************************************************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libgstreamer1.0-dev)
skipping: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libgstreamer-plugins-base1.0-dev)
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Download LibFFI6 v3.2.1_8 For Ubuntu 20 or 22 on S390X] *******************************************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Install LibFFI6 v3.2.1_8 For Ubuntu 20 or 22 on S390X] ********************************************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Set default java version for x86_64] **************************************************************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Set default java version for armv7l] **************************************************************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Set default java version for ppc64le] *************************************************************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Install 'locales' package] ************************************************************************************************************************************************************************
ok: [ubuntu22-docker-test-1.fyre.ibm.com]
```
In the above example, the `build_tools` are skipped as expected.


> Alpine failed on the curl role
Ubuntu 22.04 failed on the ant role (trying to do the GPG signature validation)
CentOS7 failed in Common : Set Default JRE (CentOS 7 and later) with 'dict object' has no attribute 'lnk_source'

maybe the packages needed for `curl`, `ant` are part of tasks having `build_tools` tags.
I've no idea what happend with the `Default JRE` one.

**Comment by aswinkr77** [comment]
@sxa 
My first approach was to use tags to run tasks, for that to work, the tags from tasks should be present in the `main.yml` file of Common role(so that tags will be picked up by ansible). But when I tested that changes(my first PR was about it), the entire Common role was skipped because some of the tags used in the main.yml was used as skip tags, so all the vagrant failed. So I changed my approach.
Now I'm using tags to skip tasks to achieve the goal, so basically as of now only `--skip-tags` will work and not `-t`:
```
ansible-playbook -u root -i ~/aswin_list.txt --tags build_tools ibm_main.yml --ssh-common-args='-o StrictHostKeyChecking=no'

PLAY [all] *******************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************
ok: [ubuntu22-docker-test-1.fyre.ibm.com]

PLAY RECAP *******************************************************************************************************************************************************************************************************
ubuntu22-docker-test-1.fyre.ibm.com : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
the example shown here is using a customized play level ibm_main.yml file, somehow the main.yml is running all the roles, instead of running only the roles/tasks associated with the particular tags specified in `--tags`.

> With -t build_tools I get GPG signature failures when it gets to the the cmake role (e.g. on CentOS7 because wget is missing) and on Ubuntu 22.04 it fails when it gets to gcc_7 because it doesn't have xz available. So overall I think there may be some work to be done to get this into a state where it would be usable.

the `cmake` and `gcc_7` roles are not supposed to run when `-t build_tools` is used, since `cmake` and `gcc_7` uses `cmake` and `gcc_7` tags respectively. I'm not sure why it ran these roles.

The `--skip-tags` is working as expected:
```
ansible-playbook -u root -i ~/aswin_list.txt --skip-tags build_tools main.yml --ssh-common-args='-o StrictHostKeyChecking=no'

PLAY [Ansible Unix playbook] *************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************
ok: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : If ansible_processor_cpus is not defined, set to ansible_processor_cores or 1] ********************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Include OS variables] *****************************************************************************************************************************************************************************
ok: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Perform OS setup and configuration] ***************************************************************************************************************************************************************
included: /Users/aswin/Personal/Eclipse Adoptium/infrastructure/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Ubuntu.yml for ubuntu22-docker-test-1.fyre.ibm.com

TASK [Common : Install gnugp2 for S390x] *************************************************************************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Install gnupg2 for aarch64] ***********************************************************************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Add Azul Zulu GPG Package Signing Key for x86_64] *************************************************************************************************************************************************
changed: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Add Azul Zulu repository for x86_64] **************************************************************************************************************************************************************
changed: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Run apt-get upgrade] ******************************************************************************************************************************************************************************
changed: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Call Build Packages and Tools Task] ***************************************************************************************************************************************************************
included: /Users/aswin/Personal/Eclipse Adoptium/infrastructure/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/build_packages_and_tools.yml for ubuntu22-docker-test-1.fyre.ibm.com

TASK [Common : Set package manager var] **************************************************************************************************************************************************************************
ok: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Set package manager var for FreeBSD] **************************************************************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Install Test Tool Packages] ***********************************************************************************************************************************************************************
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=acl)
ok: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=perl)
ok: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=xauth)
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=xvfb)
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=binfmt-support)
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=qemu-user-static)
ok: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=unzip)
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libexpat1-dev)
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libcurl4-openssl-dev)
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=fakeroot)
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=jq)
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=gnutls-bin)
ok: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libnss3)
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libnss3-tools)
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libnss3-dev)

TASK [Common : Install additional Test Tool Packages for x86_64] *************************************************************************************************************************************************
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=pulseaudio)

TASK [Common : Install additional Packages specific to Ubuntu 16] ************************************************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libgstreamer0.10-dev)
skipping: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libgstreamer-plugins-base0.10-dev)
skipping: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libmpfr4)
skipping: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libmpfr4-dbg)
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Install additional Packages specific to Ubuntu 18] ************************************************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libgstreamer1.0-dev)
skipping: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libgstreamer-plugins-base1.0-dev)
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Download LibFFI6 v3.2.1_8 For Ubuntu 20 or 22 on S390X] *******************************************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Install LibFFI6 v3.2.1_8 For Ubuntu 20 or 22 on S390X] ********************************************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Set default java version for x86_64] **************************************************************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Set default java version for armv7l] **************************************************************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Set default java version for ppc64le] *************************************************************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Install 'locales' package] ************************************************************************************************************************************************************************
ok: [ubuntu22-docker-test-1.fyre.ibm.com]
```
In the above example, the `build_tools` are skipped as expected.


> Alpine failed on the curl role
Ubuntu 22.04 failed on the ant role (trying to do the GPG signature validation)
CentOS7 failed in Common : Set Default JRE (CentOS 7 and later) with 'dict object' has no attribute 'lnk_source'

maybe the packages needed for `curl`, `ant` are part of tasks having `build_tools` tags.
I've no idea what happend with the `Default JRE` one.

**Comment by aswinkr77** [comment]
@sxa anything on this?

**Comment by sxa** [comment]
> @sxa anything on this?

Our team has been tied up with release work since last Tuesday so have not had any time to dedicate to other work since then.

> as of now only --skip-tags will work and not -t:

Understood. It's not easy to make it work both ways :-) We'll need to thing about whether we can make that clear to people running the playbooks as it superficially feels natural that you could run with `-t build_tools` to get a machine set up for building.

> maybe the packages needed for curl, ant are part of tasks having build_tools tags.

We'll need to understand that and resolve it IMHO. It would be problematic if the playbooks weren't able to work unless those were preinstalled (maybe they are on your internal fyre systems)

**Comment by aswinkr77** [comment]
@sxa I'll summarise the changes here:

- **Alpine.yml**:
I've added `build_tools` tag for this task before the block:
```
- name: Install JDK for x64
  when: ansible_architecture == "x86_64"
  block:
  ```
   the `build_tools` tags are already there for the tasks under blocks, I just moved it before the block. That's it.
  
- **CentOS.yml**:
  I've added `build_tools` tag for this task:
```
- name: Check For Centos8 Stream
  shell: cat /etc/centos-release
  register: relfile_contents
```
  cause the `relfile_contents` variable is only used in tasks which already have `build_tools` tag.
  
- **Debian.yml**:
  Added `patch_update` tag to this task:
```
  - name: Allow https apt sources
  package: "name=apt-transport-https state=latest"
```

- **Fedora.yml**:
Added `install_java` tag to 4 tasks which basically installs java:
```
################
# Install Java #
################
- name: Install Java (Not RedHat 6 on ppc64)
  package: "name={{ item }} state=latest"
  with_items: "{{ Java_NOT_RHEL6_PPC64 }}"
  when:
    - not (ansible_distribution_major_version == "6" and ansible_architecture == "ppc64")
    - not (ansible_distribution_major_version == "8")
    - not (ansible_distribution_major_version == "35" and ansible_distribution == "Fedora")


- name: Install Java when RedHat 6 on ppc64
  package: "name={{ item }} state=latest"
  with_items: "{{ Java_RHEL6_PPC64 }}"
  when: (ansible_distribution_major_version == "6" and ansible_architecture == "ppc64")


- name: Install Java when RedHat 8
  package: "name={{ item }} state=latest"
  with_items: "{{ Java_RHEL8 }}"
  when: (ansible_distribution_major_version == "8")


- name: Install Java when Fedora 35
  package: "name={{ item }} state=latest"
  with_items: "{{ Java_FED35 }}"
  when: (ansible_distribution_major_version == "35" and ansible_distribution != "Fedora")

```

- **RedHat.yml**:
Similar to the above case. Added `install_java` tag:
```
################
# Install Java #
################
- name: Install Java (Not RedHat 6 on ppc64)
  package: "name={{ item }} state=latest"
  with_items: "{{ Java_NOT_RHEL6_PPC64 }}"
  when:
    - not (ansible_distribution_major_version == "6" and ansible_architecture == "ppc64")
    - not (ansible_distribution_major_version == "8")


- name: Install Java when RedHat 6 on ppc64
  package: "name={{ item }} state=latest"
  with_items: "{{ Java_RHEL6_PPC64 }}"
  when: (ansible_distribution_major_version == "6" and ansible_architecture == "ppc64")


- name: Install Java when RedHat 8
  package: "name={{ item }} state=latest"
  with_items: "{{ Java_RHEL8 }}"
  when: (ansible_distribution_major_version == "8")

```

- **SLES.yml**:
Similar for the **Alpine.yml**, I moved the `build_tools` tag before the block. Already the tasks under the blocks had the `build_tools` tag:
```
- name: Install Git SLES 12 SP5
  when: (ansible_distribution_major_version == "12" and ansible_distribution_version == "12.5")
  block:
```

- **Ubuntu.yml**:
Added `test_tools` tag to four tasks:
```
#########################
# Additional Test Tools #
#########################
- name: Install additional Test Tool Packages for x86_64
  package: "name={{ item }} state=latest"
  with_items: "{{ Test_Tool_Packages_x86_64 }}"
  when:
    - ansible_architecture == "x86_64"
  tags: test_tools


- name: Install additional Packages specific to Ubuntu 16
  package: "name={{ item }} state=latest"
  with_items: "{{ Additional_Packages_Ubuntu16 }}"
  when:
    - ansible_distribution_major_version == "16"


- name: Install additional Packages specific to Ubuntu 18
  package: "name={{ item }} state=latest"
  with_items: "{{ Additional_Packages_Ubuntu18 }}"
  when:
    - ansible_distribution_major_version == "18"


- name: Download LibFFI6 v3.2.1_8 For Ubuntu 20 or 22 on S390X
  get_url:
    url: https://mirrors.mit.edu/ubuntu-ports/pool/main/libf/libffi/libffi6_3.2.1-8_s390x.deb
    dest: /tmp/libffi6_3.2.1-8_s390x.deb
    force: no
    mode: 0755
    checksum: sha256:05e456a2e8ad9f20db846ccb96c483235c3243e27025c3e8e8e358411fd48be9
  when:
    - (ansible_distribution_major_version == "20" and ansible_architecture == "s390x") or
      (ansible_distribution_major_version == "22" and ansible_architecture == "s390x")


- name: Install LibFFI6 v3.2.1_8 For Ubuntu 20 or 22 on S390X
  apt: deb="/tmp/libffi6_3.2.1-8_s390x.deb"
  when:
    - (ansible_distribution_major_version == "20" and ansible_architecture == "s390x") or
      (ansible_distribution_major_version == "22" and ansible_architecture == "s390x")

```

ref: https://github.com/adoptium/infrastructure/pull/3580#issuecomment-2225260133
So I don't think these changes were the causes for the failures you mentioned:
- Basically Nothing changed in **Alpine.yml**
- For Ubuntu the changes were addition of `test_tools` so there was no changes related to `build_tools`, failure was something unrelated.
- For CentOS 7, this was the task that failed: 
```
- name: Set Default JRE (CentOS 7 and later)
  alternatives:
    name: java
    path: "{{ jre_path.stat.lnk_source }}/bin/java"
  when:
    - ansible_distribution_major_version > "6"
  tags: default_java
 ```
 The only change I made was to add `build_tools` tag to the `Check for CentOS Stream` task. So the failure is unrelated.
 

> We'll need to understand that and resolve it IMHO. It would be problematic if the playbooks weren't able to work unless those were preinstalled (maybe they are on your internal fyre systems)

The failures are unrelated to changes I made. The failures are all related to the existing PB I believe.

**Comment by sxa** [comment]
> The failures are unrelated to changes I made. The failures are all related to the existing PB I believe

OK understood - I do feel we should probably try to resolve the underlying issues though. Moving and adding the existing tags doesn't seem to serve much purpose when they don't currently work. Is there a use case which would be solved by this PR given that it's already broken when skipping these days? It's difficult to approve a change that cannot be easily tested.

**Comment by aswinkr77** [comment]
@sxa 

> Moving and adding the existing tags doesn't seem to serve much purpose when they don't currently work.

They do work. See here: https://github.com/adoptium/infrastructure/pull/3580#issuecomment-2230483423
```
The --skip-tags is working as expected:

ansible-playbook -u root -i ~/aswin_list.txt --skip-tags build_tools main.yml --ssh-common-args='-o StrictHostKeyChecking=no'

PLAY [Ansible Unix playbook] *************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************
ok: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : If ansible_processor_cpus is not defined, set to ansible_processor_cores or 1] ********************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Include OS variables] *****************************************************************************************************************************************************************************
ok: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Perform OS setup and configuration] ***************************************************************************************************************************************************************
included: /Users/aswin/Personal/Eclipse Adoptium/infrastructure/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Ubuntu.yml for ubuntu22-docker-test-1.fyre.ibm.com

TASK [Common : Install gnugp2 for S390x] *************************************************************************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Install gnupg2 for aarch64] ***********************************************************************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Add Azul Zulu GPG Package Signing Key for x86_64] *************************************************************************************************************************************************
changed: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Add Azul Zulu repository for x86_64] **************************************************************************************************************************************************************
changed: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Run apt-get upgrade] ******************************************************************************************************************************************************************************
changed: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Call Build Packages and Tools Task] ***************************************************************************************************************************************************************
included: /Users/aswin/Personal/Eclipse Adoptium/infrastructure/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/build_packages_and_tools.yml for ubuntu22-docker-test-1.fyre.ibm.com

TASK [Common : Set package manager var] **************************************************************************************************************************************************************************
ok: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Set package manager var for FreeBSD] **************************************************************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Install Test Tool Packages] ***********************************************************************************************************************************************************************
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=acl)
ok: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=perl)
ok: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=xauth)
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=xvfb)
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=binfmt-support)
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=qemu-user-static)
ok: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=unzip)
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libexpat1-dev)
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libcurl4-openssl-dev)
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=fakeroot)
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=jq)
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=gnutls-bin)
ok: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libnss3)
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libnss3-tools)
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libnss3-dev)

TASK [Common : Install additional Test Tool Packages for x86_64] *************************************************************************************************************************************************
changed: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=pulseaudio)

TASK [Common : Install additional Packages specific to Ubuntu 16] ************************************************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libgstreamer0.10-dev)
skipping: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libgstreamer-plugins-base0.10-dev)
skipping: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libmpfr4)
skipping: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libmpfr4-dbg)
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Install additional Packages specific to Ubuntu 18] ************************************************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libgstreamer1.0-dev)
skipping: [ubuntu22-docker-test-1.fyre.ibm.com] => (item=libgstreamer-plugins-base1.0-dev)
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Download LibFFI6 v3.2.1_8 For Ubuntu 20 or 22 on S390X] *******************************************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Install LibFFI6 v3.2.1_8 For Ubuntu 20 or 22 on S390X] ********************************************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Set default java version for x86_64] **************************************************************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Set default java version for armv7l] **************************************************************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Set default java version for ppc64le] *************************************************************************************************************************************************************
skipping: [ubuntu22-docker-test-1.fyre.ibm.com]

TASK [Common : Install 'locales' package] ************************************************************************************************************************************************************************
ok: [ubuntu22-docker-test-1.fyre.ibm.com]
In the above example, the build_tools are skipped as expected.
```

> Is there a use case which would be solved by this PR given that it's already broken when skipping these days?

The use case is basically to skip all related tasks. For example, we sometimes(IBM) won't be needing tasks related to `build_tools`, so we can easily skip all those related tags. Also we can also skip `install_java` in RedHat, since we are not using it. These are some of the use cases.

**Comment by sxa** [comment]
One more VPC run at https://ci.adoptium.net/job/VagrantPlaybookCheck/2034/

**Comment by karianna** [comment]
> One more VPC run at https://ci.adoptium.net/job/VagrantPlaybookCheck/2034/

Run seemed to have failures but not sure if unrelated.

**Comment by Haroon-Khel** [comment]
The centos6 and ubuntu16 errors do look unrelated

**Comment by sxa** [comment]
> > One more VPC run at https://ci.adoptium.net/job/VagrantPlaybookCheck/2034/
> 
> Run seemed to have failures but not sure if unrelated.

Yep as Haroon says I'm not concerned about those in this case.

**Comment by sxa** [comment]
I've resolved a merge conflict on this so it's running through the github checks again. I think this is safe to go in now. Noting that some doc on this (particularly the fact they can be used to `--skip-tags` but not `--tags`) will form part of https://github.com/adoptium/infrastructure/issues/3012

**Review by karianna — APPROVED** [review]

**Pull request merged**
