### PR TITLE
UnixPB: Update URL For Maven GPG Signature

### PR DESCRIPTION
**Pull request by steelhead31**
Update URL to download Maven 3.6.3 GPG signature file.

##### Checklist

- [X] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)

### CODE REVIEW

**Comment by steelhead31** [comment]
Playbook runs ok locally on vagrant.

**Comment by steelhead31** [comment]
VPC run: https://ci.adoptium.net/job/VagrantPlaybookCheck/1690/

**Review by karianna — APPROVED** [review]
should move to Maven 3.9.3 at some point

**Review by Haroon-Khel — APPROVED** [review]

**Review by sxa — APPROVED** [review]
Approving on the basis that the subsequent [VPC 1961 ](https://ci.adoptium.net/job/VagrantPlaybookCheck/OS=CentOS7,label=vagrant/1691/) looks good

**Pull request merged**
