### PR TITLE
unixPB: Add alpine 3.14 container for docker host

### LINKED ISSUE #2064: Add static Docker container with Alpine Linux 3.14 for testing
So far, we have static Docker containers with Alpine Linux 3.11 and 3.12 for testing purposes. Alpine Linux 3.14 was released recently, so it's about time that we add a container for testing with Alpine Linux 3.14.

### Step 1: Add a Dockerfile with Alpine Linux 3.14

The Dockerfiles reside in `https://github.com/AdoptOpenJDK/openjdk-infrastructure/tree/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles`. You can use the one [for Alpine Linux 3.11](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.alp311) as an example.

### Step 2: Register the Dockerfile in the Ansible playbooks

The container won't magically appear on a machine. It has to be registered in our Ansible playbooks so that during the next machine re-configuration the container is added to the machine and started. To do so, you have to make two changes.

Add the newly created container to this block which is responsible for building the containers:
 
https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/6362d8ce258aebded8b33a1c7764b10ef915afa4/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/tasks/main.yml#L28-L37

Add another block similar to this one that starts the container:

https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/6362d8ce258aebded8b33a1c7764b10ef915afa4/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/tasks/main.yml#L79-L82

Here, you have to make a couple of changes:

* Pick a free SSH port on the host machine. The old block is using 2229 (`2229:22`). Take the next free number. At the time of writing, this would be 2230.
* Update the name of the container accordingly. It should be `<dockerfile suffix>.<portnumber>`. If the Dockerfile suffix is alp313 and the port number 2230, that would result in `alp313.2230`.
* Update the image name. The format is `aqa_<dockerfile suffix>`. If the Dockerfile suffix is alp313, the result would be `aqa_alp313`.

### Step 3: Test whether your container is good

* [ ] You can log into it via SSH.
* [ ] You can copy a file into it with SCP.
* [ ] The timezone is set to UTC.
* [ ] The Locale (environment variables `LANG`, `LANGUAGE`, `LC_ALL`) is set to `en_US.UTF-8`.
* [ ] You can run our test suite successfully.

To run a part of our test suite, perform the following steps within the container:

1. Download AdoptOpenJDK for Alpine Linux from https://adoptopenjdk.net/releases.html?variant=openjdk16&jvmVariant=hotspot.
2. Unpack it and set the root folder of the unpacked JDK as `TEST_JDK_HOME`, for example `export TEST_JDK_HOME=/home/jenkins/jdk-16+36`.
3. Configure the BUILD_LIST: `export BUILD_LIST=system`
4. Run the test:
   ```shell
   $ git clone https://github.com/AdoptOpenJDK/openjdk-tests.git
   $ cd openjdk-tests
   $ ./get.sh
   $ cd TKG
   $ make compile
   $ make _sanity.system
   ```

### PR DESCRIPTION
**Pull request by jeffalder**
Fixes #2064 

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [x] [FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate
- [x] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- n/a ~for inventory.yml changes, bastillion/nagios/jenkins updated accordingly~

### CODE REVIEW

**Comment by jeffalder** [comment]
Added 07992ba to align with #2280 .

**Review by karianna — APPROVED** [review]
lgtm

**Comment by jeffalder** [comment]
rebased to re-sign commits and make email address public.

**Review by sxa — CHANGES_REQUESTED** [review]
Hmmm I get an error with the `--check` option on `sha512sum` with this. Did you not see the same problem @jeffalder?
```
Step 7/20 : RUN echo "0fd2771dca2b8b014a4cb3246715b32e20ad5d26754186d82eee781507a183d5e63064890b95eb27c091c93c1209528a0b18a6d7e6901899319492a7610e74ad  /tmp/ant-contrib.tgz" >> /tmp/ant.sha512
 ---> Running in 17bb185fe06f
Removing intermediate container 17bb185fe06f
 ---> 81b1149766de
Step 8/20 : RUN sha512sum --check --strict /tmp/ant.sha512
 ---> Running in c23d8d44ac29
sha512sum: unrecognized option: check
BusyBox v1.33.1 () multi-call binary.

Usage: sha512sum [-c[sw]] [FILE]...

Print or check SHA512 checksums

	-c	Check sums against list in FILEs
	-s	Don't output anything, status code shows success
	-w	Warn about improperly formatted checksum lines
The command '/bin/sh -c sha512sum --check --strict /tmp/ant.sha512' returned a non-zero code: 1
```

**Comment by jeffalder** [comment]
@sxa  sorry about that, fixed the command in 096b3bc.

**Comment by jeffalder** [comment]
I would have tested this, but IIRC I was unable to get VirtualBox running without access to secrets, despite several hack attempts.

**Comment by sxa** [comment]
> I would have tested this, but IIRC I was unable to get VirtualBox running without access to secrets, despite several hack attempts.

Hmm if you can ping me on slack/twitter (or we can just start another issue in this repo) I'd be intererestedin hearing about this in more detail - I want these to be usable by everyone so even if just for documentation purposes I'd be keen to hear about the details of the failure you encountered :-)
At the very least, if you skip the `adoptopenjdk` and `jenkins` tags (as mentioned in the [ansible quickstart guide](https://github.com/adoptium/infrastructure/blob/master/ansible/README.md#quickstart-guide)) that is generaly enough to let anyone run through them

**Comment by sxa** [comment]
@Haroon-Khel Can you get this deployed on our machines. We should probably look at getting rid of some of the earlier versions and use 3.14 in preference now

**Comment by Haroon-Khel** [comment]
@sxa Got it deployed on dockerhost-equinix-ubuntu2004-x64-2. Its up and running in jenkins at https://ci.adoptopenjdk.net/computer/test-docker-alpine314-x64-1/

alpine 3.11 and 3.12 are running on dockerhost-equinix-ubuntu2004-x64-1. If you have no objection, I'll stop those docker containers

**Comment by Haroon-Khel** [comment]
Also, does `fakeroot` need to be added to the apk install list?

**Comment by jeffalder** [comment]
I've lost interest in continuing this, I'm going to close it.

**Comment by sxa** [comment]
> @sxa Got it deployed on dockerhost-equinix-ubuntu2004-x64-2. Its up and running in jenkins at https://ci.adoptopenjdk.net/computer/test-docker-alpine314-x64-1/
> 
> alpine 3.11 and 3.12 are running on dockerhost-equinix-ubuntu2004-x64-1. If you have no objection, I'll stop those docker containers

Let's keep them going for now, although if we start to hit capacity problems we can shut them down again.

Unsure on which systems we require `fakeroot` on, although on the basis that no-one has objected to it not being on the existing Alpine boxes we're probably ok, but I'll let @sophia-guo comment on whether it's been viisble as a problem there so far since she put in the request for `fakeroot` on the main Linux machines.

@jeffalder Your work on this PR looks good and is complete now and since the new container has been deployed by @Haroon-Khel using your dockerfile we should definiteiy merge this as it's now in production :-)

**Review by sxa — APPROVED** [review]

**Comment by sxa** [comment]
In the absence of a reply from @sophia-guo I'm going to assume this is OK - we can resolve later if required.

**Pull request merged**
