### PR TITLE
docker: Copy from the correct directory in Centos6 and Alpine dockerfiles

### PR DESCRIPTION
**Pull request by Haroon-Khel**
- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [x] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

ref https://github.com/adoptium/infrastructure/issues/2760

Revert `copy directory` changes that I made in https://github.com/adoptium/infrastructure/pull/2751/files#diff-cdadf2592f693c4816b592c519b913084ed2de4a238be6dbf42f75464798334bL7

The changes to which level of the infra repo gets copied are obsolete in that pr since I was able to get the SHA to be passed in as a parameter. More so, these changes are causing a build failure on our alpine images in the centos7_docker_image_updater job

https://ci.adoptopenjdk.net/job/centos7_docker_image_updater/268/execution/node/63/log/
https://ci.adoptopenjdk.net/job/centos7_docker_image_updater/268/execution/node/77/log/

```
Step 4/7 : COPY ../. /infrastructure
COPY failed: forbidden path outside the build context: ../. ()
```

### CODE REVIEW

**Comment by Haroon-Khel** [comment]
ref https://github.com/adoptium/infrastructure/issues/2760

**Comment by zdtsw** [comment]
is passing SHA1 to ansible-playbook `"git_sha=$git_sha"` covering all cases? if so,  
```
name: Get Latest git commit SHA
  shell: git rev-parse HEAD
  register: git_output
  delegate_to: localhost
  ignore_errors: yes
  when: git_sha is not defined
```
is not needed? otherwise, still need to run "git rev-parse HEAD" which works with "copy . /ansible" ?

**Comment by Haroon-Khel** [comment]
@zdtsw The choice of passing `"git_sha=$git_sha"` as a parameter, which we now do with these pr workflows, and the `name: Get Latest git commit SHA` task should cover all cases (unless im mistaken) 

> otherwise, still need to run "git rev-parse HEAD" which works with "copy . /ansible" ?

From https://github.com/adoptium/infrastructure/pull/2751#issuecomment-1259348795, we see that if we do copy the top level directory, theres no `.git` folder anyway, so this ansible task will not work with the pr workflows to provide a SHA

**Comment by zdtsw** [comment]
> @zdtsw Is there anything preventing this from being merged?
> 
> ping @sxa for review

sorry, forgot to follow this PR up.

**Review by zdtsw — APPROVED** [review]

**Review by sxa — APPROVED** [review]
> @sxa Ideally all build images should have it passed in and saved in the log file, but i've been focusing on alpine and centos6 recently since theyre in the github workflows and were stopping #2751 from getting merged. I can focus on the remaining build images too, but thats for a separate pr

Oh so it's because 2751 only modified those two and not the others. OK, but let's aim to get everything back in sync ASAP.

**Pull request merged**
