### PR TITLE
unixPB: add checksums for ant and ant-contrib everywhere

### LINKED ISSUE #1954: Verify downloads in static Dockerfiles
#1925 introduced Dockerfiles in `ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/` that download a couple of things (ant, ant-contrib). We should check their checksums after downloading.

### PR DESCRIPTION
**Pull request by jeffalder**
Fixes #1954 

SHA-512 for ant-1.10.5 was downloaded from the [same site](https://archive.apache.org/dist/ant/binaries/apache-ant-1.10.5-bin.zip.sha512); I was not immediately able to identify a secondary trusted source.

changed `-c` to `--check` because longer options serve as better self-documentation.
added `--strict` because otherwise sha512sum will silently ignore malformatted lines (seems suboptimal, but ok)

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- n/a ~[FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate~
- n/a ~other documentation is changed or added (if applicable)~
- n/a ~playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)~
- n/a ~for inventory.yml changes, bastillion/nagios/jenkins updated accordingly~

### CODE REVIEW

**Comment by jeffalder** [comment]
Oh yeah - I built all the docker images locally.

**Review by sxa — CHANGES_REQUESTED** [review]
As per comment in [the other PR](https://github.com/adoptium/infrastructure/pull/2277#pullrequestreview-747861877) the `--check` on `sha512sum` doesn't appear to work on Alpine (checked Alpine 313 in this PR)
```
Step 8/20 : RUN sha512sum --check --strict /tmp/ant.sha512
 ---> Running in 5e073c0b5769
sha512sum: unrecognized option: check
BusyBox v1.32.1 () multi-call binary.
```

**Comment by jeffalder** [comment]
@sxa Thanks for looking; I'll fix this up. It's disappointing that the busy-box version is so limited.

**Comment by jeffalder** [comment]
@sxa reverted those changes in 7c9a48f3ee7e49060e8e8e3f50900b3845cbedb8. Also merged master.

**Comment by sxa** [comment]
Re-running VPC checks at https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/1241/console

**Comment by jeffalder** [comment]
@sxa looks like the check failed on some platforms, not sure where to go from here.

**Comment by jeffalder** [comment]
I've lost interest in continuing this, I'm going to close it.

**Comment by sxa** [comment]
None of the failures in my VPC run is related to this PR (although they need to be resolved separately), so I'm personally ocmfortable with merging it at this point. Sorry you've found this a bit disheartening and I hope it won't put you off contributing in the future :-)

**Review by sxa — APPROVED** [review]

**Pull request merged**
