### PR TITLE
Remove deprecated Windows 2016 Docker image (O/S no longer in support)

### PR DESCRIPTION
**Pull request by karianna**
##### Checklist

- [ ] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Review by gdams — APPROVED** [review]

**Review by Willsparker — COMMENTED** [review]
We may as well remove the Win2016 Vagrantfile entirely - It's not part of VPC, and I assume there's no scope to add it to VPC, if it's out of support :-)

**Comment by karianna** [comment]
> We may as well remove the Win2016 Vagrantfile entirely - It's not part of VPC, and I assume there's no scope to add it to VPC, if it's out of support :-)

Shall I remove the 2012 as well in that case?

**Comment by Willsparker** [comment]
We use 2012 for VPC :)

**Comment by karianna** [comment]
> We use 2012 for VPC :)

Updated, I think I caught all of the references

**Comment by karianna** [comment]
It does beg the question of whether we should add 2019/2022 instead.

**Comment by Willsparker** [comment]
I certainly wouldn't be opposed to adding a newer one, however we'd still be blocked by #2178 . Maybe worth opening an issue as a future enhancement, after we've resolved that

**Review by Willsparker — APPROVED** [review]
LGTM

**Comment by sxa** [comment]
@karianna Would be good to have 2019 since you have requested to use that for JDK19 #2490 

I've resolved the merge conflicts in this so I'm going to merge it once the checks pass since it's been sitting for a while :-)

**Pull request merged**
