### PR TITLE
AIXpb: version02: `cleanup` stage 02

### PR DESCRIPTION
**Pull request by aixtools**
- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

## Change Summary
- main.yml: rewrite paging space task so no reboot is needed, localize variables; only one bootjdk role called
- roles/bootjdk/tasks/main.yml: rewrite task to use include_tasks: and move/rewrite tasks into includeable tasks; localize variables
- roles/aixfs/tasks/main.yml: remove /usr from the list and include a chfs.yml task for growth as needed by bootjdk

### CODE REVIEW

**Review by sej-jackson — APPROVED** [review]
Looks good to me - happy to merge :)

**Review by sxa — COMMENTED** [review]
Generally good, although I'd prefer if we left the list of versions of the JDK to install in the top level of the playbook to avoid diverging from how the other ones do it, to ease maintenance.

**Comment by aixtools** [comment]
> Generally good, although I'd prefer if we left the list of versions of the JDK to install in the top level of the playbook to avoid diverging from how the other ones do it, to ease maintenance.

My idea - moving forward - made applicable for all playbooks - is to have the jdk versions to be installed assigned to a variable, and processed as a list. I'll even take that task upon myself for both all platforms. Will just need some assistance in learning how to test - adequately - on non-AIX platforms :)

**Review by sxa — APPROVED** [review]
> My idea - moving forward - made applicable for all playbooks [...]

I was hoping to get a review from Will, but I'll approve and merge this one for now, and we can (hopefully!) get wider input from those who are involved in the playbooks generally.

> Will just need some assistance in learning how to test - adequately - on non-AIX platforms :)

The simple answer is the [VPC job](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck). It uses the scripts in the [pbTestScripts](https://github.com/adoptium/infrastructure/tree/master/ansible/pbTestScripts) directory of this repository to fire up a "clean" x64 VM using [Vagrant](https://www.vagrantup.com/) and [Virtualbox](https://www.virtualbox.org/), run the playbooks on it, and optionally run a build of java along with one or two bits of the test suite (to verify if the test prereqs are available)

If you don't have access to run that job we can sort that out for you. The important parameters are `FORK` (which will be `aixtools` in your case) and `BRANCH` which is whatever branch under [your fork of this repository](https://github.com/aixtools/adoptium-infrastructure/branches) you want to test. If you ask it to build it does OpenJ9 by default just because that's the one that has the most prerequisites.

**Pull request merged**
