### PR TITLE
unixPb: Install docker on SLES15 s390x not SLES12

### PR DESCRIPTION
**Pull request by Haroon-Khel**
- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

Some fixes for errors I came across while testing the s390x parts of our playbook

https://download.opensuse.org/repositories/devel:/tools/SLE_15_SP3/ is expired, replaced with https://download.opensuse.org/repositories/devel:/tools/15.4/devel:tools.repo

The installation of Git 2.31.0 failed unless put in its own block

Remove install tasks for docker on sles 12, instead install it on sles15 s390x and x64

Add conditions for Nvidia toolkit role to prevent reinstalling it

### CODE REVIEW

**Review by sxa — COMMENTED** [review]
I'd generally prefer multiple PRs for such changes (the NVidia change has nothing to do with s390x or Docker as far as I'm aware) but I won't insist on changing this one.

Also we do have a separate [GIT_Source](https://github.com/adoptium/infrastructure/tree/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/GIT_Source) role which it might be preferable. @steelhead31 Do you know if/why we couldn't use that role on SLES in https://github.com/adoptium/infrastructure/pull/2744 ?

**Comment by steelhead31** [comment]
> I'd generally prefer multiple PRs for such changes (the NVidia change has nothing to do with s390x or Docker as far as I'm aware) but I won't insist on changing this one.
> 
> Also we do have a separate [GIT\_Source](https://github.com/adoptium/infrastructure/tree/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/GIT_Source) role which it might be preferable. @steelhead31 Do you know if/why we couldn't use that role on SLES in #2744 ?

I have a feeling it was to do with installing the curl-devel package, and limiting its impact, so the git compile from source just went in there, to reduce its scope of impact... if the demand for installing git from source is becoming more prevalent ( we do it for Solaris too... )  then expanding the git\_source role might be more appropriate now.

**Comment by sxa** [comment]
> if the demand for installing git from source is becoming more prevalent 

If anything I'd expect it to reduce as newer distributions will generally have a suitably new one - it's only an issue for systems which have old toolchains (including CentOS6)

I'll create an issue for merging SLES support into GIT_Source but it doesn't need to be done as a priority.

**Comment by Haroon-Khel** [comment]
> I'll create an issue for merging SLES support into GIT_Source but it doesn't need to be done as a priority.

@sxa Could this pr still be merged in the meantime?

**Review by sxa — APPROVED** [review]
> @sxa Could this pr still be merged in the meantime?

Yes absolutely. I'll approve on the assumption that the docker setup has been verified on SLES15

**Pull request merged**
