### PR TITLE
pbTests: Reset Solaris host key after playbook completion

### PR DESCRIPTION
**Pull request by sxa**
Hopefully fixes https://github.com/adoptium/infrastructure/issues/2244

Signed-off-by: Stewart X Addison <sxa@redhat.com>

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate
- [x] other documentation is changed or added (if applicable)
- [x] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access) [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/1201/)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Comment by sxa** [comment]
NOTE: This does not yet work

**Comment by sxa** [comment]
Taking out of draft as it got past this problem in https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/1208/OS=Solaris10,label=vagrant/console (Hit others, but we can address those separately now we have the check infrastructure working again ...)

**Review by karianna — APPROVED** [review]
LGTM

**Comment by karianna** [comment]
@sxa you happy for me to merge this?

**Review by gdams — APPROVED** [review]

**Comment by sxa** [comment]
I've completed one further check that was causing me a problem but it now looks good so I'll merge :-D

**Pull request merged**
