### PR TITLE
ansible: ignore errors on check for disabled timesyncd

### PR DESCRIPTION
**Pull request by mbarbero**
It caused a playbook failure on at least one machine for temurin-compliance.

##### Checklist
- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Comment by karianna** [comment]
Shouldn't we 'fix' the actual error?

**Comment by gdams** [comment]
For reference the machine was running Ubuntu 20.04. It couldn't find the service running so it threw an error

**Comment by Haroon-Khel** [comment]
Odd since that task was put in specifically for ubuntu 20.04 https://github.com/adoptium/infrastructure/pull/1340

**Comment by sxa** [comment]
> Shouldn't we 'fix' the actual error?

+1 particular since this was added to support Ubuntu 20.04 we need to understand this and not just ignore the error

**Comment by Haroon-Khel** [comment]
This task runs fine on my ubuntu 20.04 vm. Im not sure why the service wasnt available on the temurin-compliance machine

**Comment by sxa** [comment]
What are the errors here? If it couldn't find the service does that mean it's due to a missing package that we need to add?

**Comment by sxa** [comment]
See also https://github.com/adoptium/infrastructure/issues/2199

**Comment by mbarbero** [comment]
The issue is the following

```
TASK [NTP_TIME : Ensure systemd-timesyncd service is disabled] ******************************************************************
task path: <path>/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/NTP_TIME/tasks/main.yml:12
fatal: [jck-packet-ubuntu2004-x64-1]: FAILED! => {"changed": false, "msg": "Could not find the requested service systemd-timesyncd: host"}
```

**Comment by sxa** [comment]
Hmmm arguably if we're requiring this to be disabled or not present we should trap the latter case, but I'm OK with this going in for now on the basis of that error message.

**Review by sxa — APPROVED** [review]

**Pull request merged**
