### PR TITLE
[ansible] Download cross-build jdk11u from CI

### PR DESCRIPTION
**Pull request by luhenry**
We don't want to rely on openjdk-11-jdk from Ubuntu 20.04 repositories, it's based on Zero VM and just too slow for use as boot/build JDK.

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [x] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [x] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Comment by luhenry** [comment]
@sxa @andrew-m-leonard @Haroon-Khel @karianna could I please get a review? Thank you!

**Review by sxa — APPROVED** [review]
This is good for now, although we should likely switch to another method (e.g. pulling the Temurin early access builds) once we've started building regularly.

**Comment by luhenry** [comment]
@sxa once we have the regular builds on RISC-V, I'll make sure to start cleaning up all these little hacks that crept up as we were building support. That'll be one of these.

**Review by karianna — APPROVED** [review]

**Comment by karianna** [comment]
GH Actiona failures seem unrelated

**Pull request merged**
