### PR TITLE
ansible: Add noh7B-macos12-arm64 ip

### PR DESCRIPTION
**Pull request by fredg02**
Adding the IP for a new mac machine as described here: https://github.com/temurin-compliance/infrastructure#adding-new-machines

### CODE REVIEW

**Review by sxa — APPROVED** [review]
LGTM

**Comment by sxa** [comment]
@fredg02 Can you handle the redeploy of this playbook to pick up the new host or do you need our assistance for that?

**Comment by fredg02** [comment]
//cc: @mbarbero

**Comment by fredg02** [comment]
We don't have access to the jckservices machine. AFAIK @gdams has to handle that.

**Comment by gdams** [comment]
I'll handle the redeploy (I'll do it right now)

**Comment by gdams** [comment]
done

**Comment by fredg02** [comment]
Thanks @gdams

**Pull request merged**
