### PR TITLE
winPB: Fix broken Visual Studio 2013 role to use local installation media

### LINKED ISSUE #2178: Ansible request to fix MSVS_2013 broken installation
Ref:
- https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1160/
- https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Win2012,label=vagrant/1153/

- [ ] Missing install
- [x] Bug in ansible playbook
- [ ] Request for new playbook addition

Details:
Registering the MSVS_2013 shared libraries ([this task](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/3ecc482cd9d34545676efecab0626882321385bb/ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2013/tasks/main.yml#L26)), intermittently fails with :
```
10:59:23 TASK [MSVS_2013 : Register Visual Studio Community 2013 DIA SDK shared libraries] ***
10:59:26 failed: [127.0.0.1] (item=C:\Program Files (x86)\Microsoft Visual Studio 12.0\DIA SDK\bin\msdia120.dll) => {"ansible_loop_var": "item", "changed": true, "cmd": "regsvr32 /s \"C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\DIA SDK\\bin\\msdia120.dll\"", "delta": "0:00:00.093433", "end": "2021-05-05 09:57:05.619367", "item": "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\DIA SDK\\bin\\msdia120.dll", "msg": "non-zero return code", "rc": 3, "start": "2021-05-05 09:57:05.525933", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```
(return code 3).

There's no stderr because regsvr32 is being run with `/s`, however that may help with debugging. See: https://devblogs.microsoft.com/oldnewthing/20180921-00/?p=99795 which may give some insight. 

According to above, RC=3 means the `loadlibrary` call is failing (or that it's a red herring). Either way, removing `/s` will give some insight, so that's where I'll start.

### PR DESCRIPTION
**Pull request by steelhead31**
Update the VS2013 role to work from  local installation media.
This is only required until VS2013 is no longer used.
Fixes #2178

##### Checklist

- [X] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [x] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM

**Comment by steelhead31** [comment]
@sxa, would you mind reviewing this PR. Thanks.

**Comment by sxa** [comment]
@steelhead31 Have you got a VPC run with this PR?

**Comment by steelhead31** [comment]
> @steelhead31 Have you got a VPC run with this PR?

I've started a new one here.. https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Win2012,label=vagrant/1550/

**Comment by steelhead31** [comment]
@sxa, the VPC run built ok, there appears to be an issue with the tests, but that isnt related.

**Comment by sxa** [comment]
Yuk ... As you say:
```
22:46:27 mv: target '/home/vagrant' is not a directory
22:46:27 find: '/home/vagrant': No such file or directory
22:46:27 C:/vagrant/pbTestScripts/testJDKWin.sh: line 9: cd: /home/vagrant: No such file or directory
22:46:27 Cloning into 'openjdk-tests'...
22:46:27 Updating files:  30% (495/1635)
[...]
Updating files: 100% (1635/1635), done.
22:46:43 Invalid option: -t
22:46:47 C:/vagrant/pbTestScripts/testJDKWin.sh: line 24: cd: TKG: No such file or directory
22:46:47 make: *** No rule to make target '_extended.system'.  Stop.
```

**Review by sxa — APPROVED** [review]
LGTM now.

This could cause problems if people don't have the Vendor_Files directory with the file in it, so perhaps we should adjust the recommended commands [in the docs](https://github.com/adoptium/infrastructure/tree/master/ansible#quickstart-guide) to say that users skip `MSVS_2013` by default too. Approving whether this is done here or separately :-)

**Pull request merged**
