### PR TITLE
unixPB: Clean_Up role: remove warn: no

### PR DESCRIPTION
**Pull request by sxa**
This syntax is invalid and does not work with the new AWX server
Fixes https://github.com/adoptium/infrastructure/issues/3425

While there may be a better solution here, this will allow the deployments to continue to succeed ... I've tested this in a separate AWX template

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Comment by karianna** [comment]
@sxa Looks like various checks failed

**Review by steelhead31 — APPROVED** [review]
LGTM

**Comment by sxa** [comment]
> @sxa Looks like various checks failed

None of those seem related to the PR and are failures earlier on in the checks - would you agree?

**Comment by steelhead31** [comment]
@sxa Im just working on the fix for the labeler :)

**Review by karianna — APPROVED** [review]

**Comment by karianna** [comment]
GH action failures are unrelated.

**Pull request merged**
