### PR TITLE
UnixPB: Include check for ntpd service.

### LINKED ISSUE #3454: Centos 7 docker image update job failing
As seen in this log: https://ci.adoptium.net/job/centos7_docker_image_updater/461/execution/node/83/log/

The unix playbook role for NTP time fails inside a docker container, due to it attempting to start a service which isn't present.

The NTP_TIME role needs a fix to check if the service is present prior to attempting to start it.

### PR DESCRIPTION
**Pull request by steelhead31**
Fixes #3454 

##### Checklist

- [X] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [x] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)

VPC Completed OK: https://ci.adoptium.net/job/VagrantPlaybookCheck/1842/

### CODE REVIEW

**Review by sxa — CHANGES_REQUESTED** [review]
Can you redo the commit message to prefix it with `unixPB:` (Can be done on squash but if someone else does it it's likely to get missed.

Do we install the ntp packages in containers? Assuming yes I guess it just doesn't get registered which is why this fails?

**Comment by steelhead31** [comment]
> Can you redo the commit message to prefix it with `unixPB:` (Can be done on squash but if someone else does it it's likely to get missed.
> 
> Do we install the ntp packages in containers? Assuming yes I guess it just doesn't get registered which is why this fails?

Done, we do install NTPD, but the docker containers lack "services" , systemctl returns a bus error, which I guess is a docker thing, so I think this is probably the closes thing to a solution. It seems to work OK on Centos7 & Centos8, but the VPC on Centos6 failed, so I'll need to do a bit more investigation into that.

**Review by sxa — APPROVED** [review]
> systemctl returns a bus error

Yikes, but ok ... :-)

**Comment by steelhead31** [comment]
> > systemctl returns a bus error
> 
> Yikes, but ok ... :-)

For documentation purposes...  
  
systemd requires CAP\_SYS\_ADMIN capability but Docker drops that capability in the non privileged containers, in order to add more security... I guess we could look to implement this if required in our containers.

**Comment by steelhead31** [comment]
Rerun Of The VPC with improved handling for CentOS6..  
  
https://ci.adoptium.net/job/VagrantPlaybookCheck/1840/

**Comment by sxa** [comment]
> systemd requires CAP\_SYS\_ADMIN capability ...I guess we could look to implement this if required in our containers.

I wouldn't have thought we need it. Is hope that time sync  would be handled by the host for the containerised environment

**Comment by steelhead31** [comment]
Failing checks are known issues and not related.

**Review by gdams — APPROVED** [review]

**Pull request merged**
