### PR TITLE
UnixPb: Use wget to download ant-contrib on centos6

### PR DESCRIPTION
**Pull request by Haroon-Khel**
- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

ref https://github.com/adoptium/infrastructure/issues/2486

### CODE REVIEW

**Comment by Haroon-Khel** [comment]
Kicked off vpc https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1397/

**Comment by Haroon-Khel** [comment]
@sxa I followed the instructions in your issue. Kicked off another vpc https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1398/

**Comment by Haroon-Khel** [comment]
The centos6 docker check has passed on this pr btw so atleast we know this pr fixes that issue

**Comment by sxa** [comment]
Looks like a lot of failures in VPC around the ant contrib download, but unclear if that's this change or an outage on the HTTP server end.

**Comment by Haroon-Khel** [comment]
I've added `ca-certificates` to the ubuntu, debian, centos and rhel install lists. Kicked off another vpc https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1399/

**Comment by Haroon-Khel** [comment]
Ubuntu 16+ and centos7+ have a 2021 ca-certifcates package available for them in their respective package manager repo. Centos 6 does not. I thought I fixed Centos 6's issue (earlier centos6 pr check was able to download ant-contrib fine) but the vpc still shows that it is having trouble downloading ant-contrib

**Comment by Haroon-Khel** [comment]
Centos 6 VPC and Docker check now seem to be experiencing a network issue when connecting to Centos mirror

[VPC](https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1399/OS=CentOS6,label=vagrant/console)

```
TASK [CentOS6-Cent7SSL : Install prereqs for building ca-certificate bundle ...] ***
16:59:05 fatal: [127.0.0.1]: FAILED! => {"changed": false, "changes": {"installed": ["asciidoc", "java-1.6.0-openjdk"]}, "msg": "https://vault.centos.org/centos/6/os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 7 - \"Failed to connect to 2600:1f13:2e7:2901:d2b0:c3b2:9347:934c: Network is unreachable\"\nTrying other mirror.\nhttps://vault.centos.org/centos/6/extras/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 7 - \"Failed to connect to 2600:1f13:2e7:2901:d2b0:c3b2:9347:934c: Network is unreachable\
```

Docker check

```
Step 3/10 : RUN sed -i -e 's!mirrorlist!#mirrorlist!g' /etc/yum.repos.d/CentOS-Base.repo;     sed -i -e 's!#baseurl=[http://mirror.centos.org/centos/\$releasever!baseurl=https://vault.centos.org/6.10/!g](http://mirror.centos.org/centos//$releasever!baseurl=https://vault.centos.org/6.10/!g)' /etc/yum.repos.d/CentOS-Base.repo;     yum -y update; yum clean all;     yum -y install gcc openssl-devel bzip2-devel sqlite-devel sudo wget python3 epel-release;     yum -y install ansible
 ---> Running in 5bdbf0d52442
Loaded plugins: fastestmirror, ovl
Setting up Update Process
https://vault.centos.org/6.10//os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 7 - "Failed to connect to 2600:1f16:c1:5e03:a992:8ee1:99d2:6f8: Cannot assign requested address"
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: base. Please verify its path and try again
Loaded plugins: fastestmirror, ovl
Cleaning repos: base extras updates
Cleaning up Everything
Loaded plugins: fastestmirror, ovl
Setting up Install Process
Determining fastest mirrors
https://vault.centos.org/6.10//os/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 7 - "Failed to connect to 2600:1f13:2e7:2901:d2b0:c3b2:9[34](https://github.com/adoptium/infrastructure/runs/5379065682?check_suite_focus=true#step:4:34)7:934c: Cannot assign requested address"
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repositor
```

Possibly intermittent https://github.com/actions/virtual-environments/issues/2264. Will kick off another centos6 vpc when Previous vpc job finishes

**Comment by Haroon-Khel** [comment]
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1399/
Upgrading ca-certificates at the beginning of the playbook run seems to have fixed those OS's that failed earlier. Centos8 is still acting up, but due to an issue unrelated to this pr 

Kicked off a Centos6 only VPC
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1400/

**Comment by Haroon-Khel** [comment]
VPC and Docker pr check both passed. I think this can be merged

**Review by sxa — APPROVED** [review]
👍🏻

**Pull request merged**
