### PR TITLE
docker: New dockernode.yml playbook to automate deployment of docker static containers

### PR DESCRIPTION
**Pull request by Haroon-Khel**
- [ ] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

ref https://github.com/adoptium/infrastructure/issues/3370

New playbook added `dockernode.yml `which will deploy any number of specified containers onto a chosen dockerhost machine. Example usage: (will add to docs)

```
ansible-playbook AdoptOpenJDK_Unix_Playbook/dockernode.yml -t deploy -e "docker_images=u2204,alp314,deb11"
```

The `deploy` tag must be specified if the user wants to deploy a container. The `docker_images` variable will contain a list of chosen OSs for which we have dockerfiles (error is handled when dockerfile does not exist).

I am testing this at the moment in awx. Once successful we can remove the container build and deploy functionality in https://github.com/adoptium/infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/tasks/main.yml and leave the `dockerhost.yml` playbook for setting up dockerhost machines only, and use the new `dockernode.yml` playbook for deploying containers

### CODE REVIEW

**Review by karianna — APPROVED** [review]

**Comment by Haroon-Khel** [comment]
The changes work
```
69e6c452d007   aqa_u2204      "/usr/sbin/sshd -D"   7 minutes ago   Up 7 minutes   0.0.0.0:32769->22/tcp, :::32769->22/tcp   U2204.32769
```

**Comment by Haroon-Khel** [comment]
Going to create some containers on dockerhost-osuosl-ubuntu2204-aarch64-1  ref https://github.com/adoptium/infrastructure/issues/2991

**Review by sxa — CHANGES_REQUESTED** [review]
Looks good overall but a few things - I'd block merging on the first of these in particular:
- Can you add something into the top of each file to explain specifically what it does
- If we're going to test this on some systems for real deployments this week can we update some of the dockerfiles to use up to date OSs e.g. Fedora 39, Alpine 3.19 and Ubuntu 23.10 since a few of the ones we have just now are already out of support as per https://github.com/adoptium/infrastructure/wiki/End-of-support-date-for-OS-distributions?
- Is there any way we can incorporate https://github.com/adoptium/infrastructure/issues/3345 into this somehow to give each one a unique hostname?

**Comment by Haroon-Khel** [comment]
Ive updated some of the dockerfiles but will udpate the rest as part of the `Create templates for dockerfiles, removing the need to have a different file for each new release of OS` issue of the epic https://github.com/adoptium/infrastructure/issues/3368

**Comment by sxa** [comment]
@karianna My original review still stands until there are comments added to the top of the two `.yml` files in the new `deploy_container` role.

**Comment by Haroon-Khel** [comment]
> Is there any way we can incorporate https://github.com/adoptium/infrastructure/issues/3345 into this somehow to give each one a unique hostname?

I would like to incorporate this in a separate pr, alongside the `Automate creation of node in jenkins after deploying static container` part of the https://github.com/adoptium/infrastructure/issues/3368 epic.

**Comment by Haroon-Khel** [comment]
The alpine311 and fedora35 dockerstatic checks are failing because I have replaced their dockerfiles with alpine319 and fedora39 respectively. I will update the workflow in a separate pr

**Review by sxa — APPROVED** [review]
LGTM

**Pull request merged**
