### PR TITLE
aixPB: Add security role for basic hardening steps

### LINKED ISSUE #2205: Ansible request for AIX: osuosl (and others?)
Please put the name of the software product (and affected platforms if relevant) in the title of this issue

- [ ] Missing install
- [ ] Bug in ansible playbook
- [x] Request for new playbook addition

Details:
Recent security scans at OSUOSL show potential vulerabilities.

This issue is to track the changes being tested - before being put into a new playbook, or modifying an existing playbook.

Deeper details are discussed within the security related slack channel.

### PR DESCRIPTION
**Pull request by aixtools**
Fix #2205
##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Comment by aixtools** [comment]
Would someone please review this.

**Review by karianna — COMMENTED** [review]
LGTM but ansible linter is complaining about things like:

ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/security/tasks/main.yml#L7
ignore-errors Use failed_when and specify error conditions instead of using ignore_errors

**Comment by aixtools** [comment]
The possible error is that the fileset is already removed (line 18).

I tested manually, and the ignore_errors at line 7 can be removed, because even when disabled, the status is 0.

And, perhaps it is better to signal an error if the agent is not removed successfully.

Making changes.

**Comment by aixtools** [comment]
Well, that was an interesting challenge.

**Comment by aixtools** [comment]
@karianna - can you check again please.

**Review by karianna — APPROVED** [review]
LGTM

**Comment by aixtools** [comment]
closing: already done via #2453

**Pull request closed without merging**
