### PR TITLE
AIXPb: Enable ansible logs on aix machines

### PR DESCRIPTION
**Pull request by Haroon-Khel**
ref https://github.com/adoptium/infrastructure/issues/2202

- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

Added logs feature to the aix playbook, and also tidied all of the roles that were in the main.yml file while they should be in their own directory

I have also removed the block below from the main.yml for two reasons. One, the playbook gets run with the root user of the remote machine anyway. Two, if the first reason is not sufficient for some reason and the code block is still required for some tasks it should be added to those tasks that need it and not to the main.yml file
```
  remote_user: root
  become: true
```
For example, having this in the main.yml prevents this task in the logs role from running
```
- name: Get Latest git commit SHA
  shell: git rev-parse HEAD
  register: git_output
  delegate_to: localhost
  ignore_errors: yes
  when: git_sha is not defined
```
When ansible tries to delegate this task to localhost (the machine running the ansible playbook) it tries to run it as root which is not necessary and requires a sudo password which causes the playbook to exit.

So the question is which tasks do need the removed code block, and will removing it prevent those tasks from running. I'll soon find this out by testing this pr

### CODE REVIEW

**Review by karianna — CHANGES_REQUESTED** [review]
Looks like linter is still sad

**Comment by sxa** [comment]
> Looks like linter is still sad

I don't think any of the failures are related to this PR unless you've seen otherwise. [#2737](https://github.com/adoptium/infrastructure/issues/2906) covers the failures

**Comment by sxa** [comment]
FYI @sej-jackson @AdamBrousseau in case you want to look over this

**Comment by Haroon-Khel** [comment]
This pr is ready to merge. I've rebased so it picks up https://github.com/adoptium/infrastructure/pull/2919 which looks like it has fixed some of the linter errors but not all. The remaining error 
`ERROR! Attempting to decrypt but no vault secrets found`
does not seem related to this pr

**Comment by Haroon-Khel** [comment]
@sxa for review and @karianna for rereview

**Comment by sxa** [comment]
Has this undergone much testing? I'd have preferred the refactor to have been in a separate PR to make the logging functionality easier to review, but if this has been tested somewhere please let me know. I'd also like @aixtools to review if possible since I know he was also keen to have the top level file split into individual roles.

**Comment by Haroon-Khel** [comment]
>Has this undergone much testing? I'd have preferred the refactor to have been in a separate PR to make the logging functionality easier to review, but if this has been tested somewhere please let me know. I'd also like @aixtools to review if possible since I know he was also keen to have the top level file split into individual roles.

Yes I have run it on an existing AIX machine. No errors. The refactoring was necessary for the "end" logs to run at the end of the playbook. To elaborate, the `roles:` portion of the `main.yml` file get run first, before the `tasks:` portion. So with the end `logs` role, despite me wanting it to run at the end of the playbook, it would have run only at the end of the `roles` portion and before the `tasks`, hence why I had to refactor the `tasks` so everything can be in `roles`

**Review by karianna — APPROVED** [review]

**Comment by karianna** [comment]
Separate PR should probably go in for the linter

**Review by sxa — APPROVED** [review]
I'm ok with this but I might be tempted to hold off on merging since the AIX build machines are currently unstable - see:
- https://github.com/adoptium/infrastructure/issues/2936
- https://github.com/adoptium/infrastructure/issues/2922

**Comment by sxa** [comment]
> I'm ok with this but I might be tempted to hold off on merging since the AIX build machines are currently unstable - see:
> 
> * #2936
> * #2922

Since one of these has been fixed and the cause of the other is understood (although no final fix identified) I'm ok with this going in now if you want to merge it @Haroon-Khel

**Pull request merged**
