### PR TITLE
WinPB: Update Wix Installation To Install SDK

### LINKED ISSUE #3617: Ansible Windows Playbook Fails On Wix 5.0 Installation / Windows Server 2022
Please put the name of the software product (and affected platforms if relevant) in the title of this issue

Delete as appropriate from this list:

- Bug in ansible playbook

Details:

The Windows playbook fails when trying to install Wix 5.0 using the "dotnet tool" installation method.

### PR DESCRIPTION
**Pull request by steelhead31**
Update the Wix5 installation task, as the .NET SDK is not installed by default, and the wix installation requires it.

This also addresses a bug, where the playbook incorrectly uses sudo as a become method, which should be runas in Windows.

Fixes #3617 

##### Checklist

- [X] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [X] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)

### CODE REVIEW

**Review by andrew-m-leonard — APPROVED** [review]
lgtm

**Comment by gdams** [comment]
I've just been chatting to the .NET team, there are [dotnet-install scripts](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script) you can use. For example:

```powershell
# Windows PowerShell
Invoke-WebRequest -Uri https://dot.net/v1/dotnet-install.ps1 -OutFile "$env:temp/dotnet-install.ps1"; powershell -executionpolicy bypass "$env:temp/dotnet-install.ps1"

# PowerShell Core
Invoke-WebRequest -Uri https://dot.net/v1/dotnet-install.ps1 -OutFile "$env:temp/dotnet-install.ps1"; pwsh "$env:temp/dotnet-install.ps1"
```

**Comment by steelhead31** [comment]
> I've just been chatting to the .NET team, there are [dotnet-install scripts](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script) you can use. For example:
> 
> ```powershell
> # Windows PowerShell
> Invoke-WebRequest -Uri https://dot.net/v1/dotnet-install.ps1 -OutFile "$env:temp/dotnet-install.ps1"; powershell -executionpolicy bypass "$env:temp/dotnet-install.ps1"
> 
> # PowerShell Core
> Invoke-WebRequest -Uri https://dot.net/v1/dotnet-install.ps1 -OutFile "$env:temp/dotnet-install.ps1"; pwsh "$env:temp/dotnet-install.ps1"
> ```

I tried those, but they install the .net SDK in a user specific folder, which then isn't available to the jenkins user.. as we run the playbooks as an administrator user, but these tools are needed for the jenkins user.

**Comment by gdams** [comment]
> > I've just been chatting to the .NET team, there are [dotnet-install scripts](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script) you can use. For example:
> > ```powershell
> > # Windows PowerShell
> > Invoke-WebRequest -Uri https://dot.net/v1/dotnet-install.ps1 -OutFile "$env:temp/dotnet-install.ps1"; powershell -executionpolicy bypass "$env:temp/dotnet-install.ps1"
> > 
> > # PowerShell Core
> > Invoke-WebRequest -Uri https://dot.net/v1/dotnet-install.ps1 -OutFile "$env:temp/dotnet-install.ps1"; pwsh "$env:temp/dotnet-install.ps1"
> > ```
> 
> I tried those, but they install the .net SDK in a user specific folder, which then isn't available to the jenkins user.. as we run the playbooks as an administrator user, but these tools are needed for the jenkins user.

Can you not run them as the jenkins user?

**Comment by steelhead31** [comment]
> > > I've just been chatting to the .NET team, there are [dotnet-install scripts](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script) you can use. For example:
> > > 
> > > ```powershell
> > > # Windows PowerShell
> > > Invoke-WebRequest -Uri https://dot.net/v1/dotnet-install.ps1 -OutFile "$env:temp/dotnet-install.ps1"; powershell -executionpolicy bypass "$env:temp/dotnet-install.ps1"
> > > 
> > > # PowerShell Core
> > > Invoke-WebRequest -Uri https://dot.net/v1/dotnet-install.ps1 -OutFile "$env:temp/dotnet-install.ps1"; pwsh "$env:temp/dotnet-install.ps1"
> > > ```
> > 
> > I tried those, but they install the .net SDK in a user specific folder, which then isn't available to the jenkins user.. as we run the playbooks as an administrator user, but these tools are needed for the jenkins user.
> 
> Can you not run them as the jenkins user?

Let me give them a quick test. I had issues with the become user elements on our playbook checker ( its on an old version of ansible which has issues... that's a separate issue Im already looking into )

**Comment by steelhead31** [comment]
I've tried running both as jenkins, as it doesn't get added to the path, it ends up in a <<user>>/.dotnet folder, I think the current solution is more reliable, so I'll leave it like this, as it does work with GHA, and when running the playbooks to build normal machines.

**Pull request merged**
