### PR TITLE
docs: Update docs to include deleting docker static containers

### PR DESCRIPTION
**Pull request by Haroon-Khel**
- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [x] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

Update docs for https://github.com/adoptium/infrastructure/pull/3561

### CODE REVIEW

**Review by karianna — APPROVED** [review]

**Comment by karianna** [comment]
Mighty be worth both upgrading semgrep and fixing its complaint :-)

**Comment by steelhead31** [comment]
@Haroon-Khel / @karianna  I'll upgrade semgrep, Im just making a change to add the license text to the 3 action files I added :)

**Comment by steelhead31** [comment]
Semgrep action is now correct, however the release of semgrep from a week ago, hasn't yet been reflected into the containers. Coming soon I believe :)

**Comment by Haroon-Khel** [comment]
The changes of this pr are going in with https://github.com/adoptium/infrastructure/pull/3561. So this pr can be closed

**Pull request closed without merging**
