### PR TITLE
Enhancement: Adding windows machine to Nagios

### LINKED ISSUE #2802: Nagios: Enhancement: Document Process For Adding Windows Hosts To A Nagios Server
Part Of Epic #2445 

Please investigate the process, tasks and steps involved in adding Nagios monitoring checks to a windows host.

Please create a new document in the /ansible/playbooks/nagios folder called something like How\_To\_Add\_Nagios\_To\_Windows.MD , with detailed steps about the tasks etc on both the Nagios Server & the Windows Host, so that we can try this in production at a later date. I'd recommend using nagios etc to create a nagios server, and a windows VM, so that you have an isolated development environment.

### PR DESCRIPTION
**Pull request by lumuchris256**
Documented and tested Process i took  to add a Windows Host To a Nagios Server 
 
Output:
success3

fixes #2802 
signed off by @lumuchris256 
cc @steelhead31 @sxa @smlambert @Haroon-Khel @karianna

### CODE REVIEW

**Review by steelhead31 — APPROVED** [review]
Looks good to me, provides a good base for expanding into how we manage windows machines within the project going forward.

**Comment by zdtsw** [comment]
two questions:
1. why not install `nsclient` by ansible? from this instruction, it is manually installed on the windows machine after it is up and running?
2. not very clear from this instruction, if files (e.g` windows.cfg`) under` /usr/local/nagios/etc` are auto-created after `nsclinet` or if anything else need to be done on the windows machine?

**Comment by steelhead31** [comment]
@zdtsw  ,the first question is answered by my draft PR for our windows playbooks #2827 , for point 2, there is nothing needing to be done on the windows machine, other than the installation of nsclient. all the other work is done on the nagios server,  the automation of this is the next task. I asked @lumuchris256 to produce this document to provide a rough guide as to how to monitor windows, which could then be used as the basis for the automation work, which is why this is in a seperate .md file

> two questions:
> 
> 1. why not install `nsclient` by ansible? from this instruction, it is manually installed on the windows machine after it is up and running?
> 2. not very clear from this instruction, if files (e.g` windows.cfg`) under` /usr/local/nagios/etc` are auto-created after `nsclinet` or if anything else need to be done on the windows machine?

> * why not install `nsclient` by ansible? from this instruction, it is manually installed on the windows machine after it is up and running?
> * not very clear from this instruction, if files (e.g` windows.cfg`) under` /usr/local/nagios/etc` are auto-created after `nsclinet` or if anything else need to be done on the windows machine?

**Comment by zdtsw** [comment]
Assume, we should get this PR in first, and then https://github.com/adoptium/infrastructure/pull/2827, then remove the  "manual installation" part from this PR? 

> @zdtsw ,the first question is answered by my draft PR for our windows playbooks #2827 , for point 2, there is nothing needing to be done on the windows machine, other than the installation of nsclient. all the other work is done on the nagios server, the automation of this is the next task. I asked @lumuchris256 to produce this document to provide a rough guide as to how to monitor windows, which could then be used as the basis for the automation work, which is why this is in a seperate .md file
> 
> > two questions:
> > 
> > 1. why not install `nsclient` by ansible? from this instruction, it is manually installed on the windows machine after it is up and running?
> > 2. not very clear from this instruction, if files (e.g` windows.cfg`) under` /usr/local/nagios/etc` are auto-created after `nsclinet` or if anything else need to be done on the windows machine?
> 
> > * why not install `nsclient` by ansible? from this instruction, it is manually installed on the windows machine after it is up and running?
> > * not very clear from this instruction, if files (e.g` windows.cfg`) under` /usr/local/nagios/etc` are auto-created after `nsclinet` or if anything else need to be done on the windows machine?

**Review by zdtsw — APPROVED** [review]

**Comment by steelhead31** [comment]
> Assume, we should get this PR in first, and then #2827, then remove the "manual installation" part from this PR?
> 
> > @zdtsw ,the first question is answered by my draft PR for our windows playbooks #2827 , for point 2, there is nothing needing to be done on the windows machine, other than the installation of nsclient. all the other work is done on the nagios server, the automation of this is the next task. I asked @lumuchris256 to produce this document to provide a rough guide as to how to monitor windows, which could then be used as the basis for the automation work, which is why this is in a seperate .md file
> > 
> > > two questions:
> > > 
> > > 1.  why not install `nsclient` by ansible? from this instruction, it is manually installed on the windows machine after it is up and running?
> > > 2.  not very clear from this instruction, if files (e.g `windows.cfg`) under `/usr/local/nagios/etc` are auto-created after `nsclinet` or if anything else need to be done on the windows machine?
> > 
> > > *   why not install `nsclient` by ansible? from this instruction, it is manually installed on the windows machine after it is up and running?
> > > *   not very clear from this instruction, if files (e.g `windows.cfg`) under `/usr/local/nagios/etc` are auto-created after `nsclinet` or if anything else need to be done on the windows machine?

This is exactly the plan, as the automation project continues, the documentation will be updated to define the "current" process.. this should allow us to both track the improvements, and refer to how we got something to work in the first instance.

**Review by steelhead31 — APPROVED** [review]

**Pull request merged**
