### PR TITLE
docker: script to retrieve static docker containers from jenkins

### PR DESCRIPTION
**Pull request by Haroon-Khel**
- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [x] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

ref https://github.com/adoptium/infrastructure/issues/3415

Example output

```
[
    {
        "name": "dockerhost-equinix-ubuntu2004-armv8-1",
        "ip": "147.75.35.203",
        "containers": [
            {
                "nodeName": "test-docker-alpine319-armv8-2",
                "port": "32775"
            },
            {
                "nodeName": "test-docker-alpine319-armv8-4",
                "port": "32777"
            },
            {
                "nodeName": "test-docker-fedora39-armv8l-1",
                "port": "2234"
            },
            {
                "nodeName": "test-docker-sles15-armv8l-1",
                "port": "2236"
            },
            {
                "nodeName": "test-docker-ubuntu1804-armv8l-4",
                "port": "32774"
            },
            {
                "nodeName": "test-docker-ubuntu2004-armv7l-1",
                "port": "2322"
            },
            {
                "nodeName": "test-docker-ubuntu2004-armv7l-2",
                "port": "2323"
            },
            {
                "nodeName": "test-docker-ubuntu2004-armv7l-3",
                "port": "2332"
            },
            {
                "nodeName": "test-docker-ubuntu2004-armv8l-1",
                "port": "32770"
            },
            {
                "nodeName": "test-docker-ubuntu2004-armv8l-2",
                "port": "32771"
            },
            {
                "nodeName": "test-docker-ubuntu2004-armv8l-3",
                "port": "32772"
            },
            {
                "nodeName": "test-docker-ubuntu2204-armv8l-2",
                "port": "32773"
            },
            {
                "nodeName": "test-docker-ubuntu2310-armv8l-1",
                "port": "32776"
            }
        ],
        "containersCount": 13
    }
]
```

The credentials needed to query jenkins are going to be passed into the script via the `Vendor_Files` role, which means the credentials need to be stored in the secrets repo

### CODE REVIEW

**Review by sxa — COMMENTED** [review]
No comment on the code yet but noting the typo in the filename which will need to be fixed :-)

**Comment by Haroon-Khel** [comment]
At the moment it dumps the inventory results into `DockerInventory.json` which should stay in the same directory as inventory.yml.

I would like a system in place to keep this inventory updated. Could do an automated github action which runs the script, if it detects differences between the output and the existing `DockerInventory.json` file, it makes a pr to update it. Either way this is beyond this pr

**Review by karianna — APPROVED** [review]
code LGTM

**Review by steelhead31 — APPROVED** [review]
LGTM

**Pull request merged**
