### PR TITLE
UnixPB: Add new Ubuntu ntp plugin for nagios

### PR DESCRIPTION
**Pull request by steelhead31**
Add a new plugin for checking NTP service state on Ubuntu.

Currently the check_timesync plugin installed on Ubuntu checks only timesyncd, as we are planning to uniformly switch to NTP as part of issue #2199 we need a version of the plugin that works for Ubuntue.

##### Checklist

- [X] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [x] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)

### CODE REVIEW

**Comment by steelhead31** [comment]
VPC run at https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1599/

**Review by sxa — COMMENTED** [review]
Looks like the Ubuntu 22.04 run didn't go through in the VPC check, so we'll want to confirm that that is definitely ok before merging given it's probably the most important version :-)

**Review by sxa — APPROVED** [review]

**Review by karianna — CHANGES_REQUESTED** [review]
Looks like linters are failing but there's a later PR that might fix that.

**Review by Haroon-Khel — APPROVED** [review]
LGTM

**Pull request merged**
