### PR TITLE
WindowsPB: Update VS2022 Download Checksum

### LINKED ISSUE #3607: Windows Playbook Fails Due To Incorrect Checksum On VS2022 Community Edition Download
The Windows playbook fails, due to an updated version of the MS VS2022 CE bootstrap installer being released, and thus the checksum is incorrect.

### PR DESCRIPTION
**Pull request by steelhead31**
Update the MSVS2022 CE bootstrap checksum

Fixes #3607 

##### Checklist

- [X] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [x] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)

### CODE REVIEW

**Comment by steelhead31** [comment]
VPC in progress : https://ci.adoptium.net/job/VagrantPlaybookCheck/1879/

**Review by tellison — APPROVED** [review]

**Comment by andrew-m-leonard** [comment]
@steelhead31 Have we changed the update version of VS2022 we are building with? as this will affect reproducible builds?

**Comment by steelhead31** [comment]
> @steelhead31 Have we changed the update version of VS2022 we are building with? as this will affect reproducible builds?

Nope, its the boot strap installer, used where our default layout doesn't exist... MS occasionally update the bootstrap installer for the CE download, so the checksum periodically gets updated... it still installs the correct versions :)

**Review by sxa — APPROVED** [review]
I had one query on whether we were moving to the build tools for this, but that's not in place yet so approving.

**Pull request merged**
