### PR TITLE
fix: disable new fqcn ansible-lint rule

### PR DESCRIPTION
**Pull request by zdtsw**
-  https://github.com/ansible/ansible-lint/pull/1908 add to v6.0.0
  - GH action installing 6.0.2 ansible-lint since mid March which broke lint step
  - yamllint for .ansible-lint file
  - no-handler lint error

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [x] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [x] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Comment by zdtsw** [comment]
@Haroon-Khel could this be something relate to what  you mentioned?

**Comment by zdtsw** [comment]
@sxa could you do a review on this change? ansible-lint should be fixed

**Comment by zdtsw** [comment]
created a new issue https://github.com/adoptium/infrastructure/issues/2524 for failure in ansible /macos

**Review by sxa — APPROVED** [review]
I'm ok with this on the basis it now passes the linker, but I've requested Haroon as a reviewer too since the DockerStatic role handler affects a change he recently put in.

**Comment by zdtsw** [comment]
changes made in DockerStatic/tasks/main.yml 
is to fix error: https://github.com/adoptium/infrastructure/runs/5835956104?check_suite_focus=true#step:5:3193

**Review by Haroon-Khel — APPROVED** [review]
The dockerstatic changes look good to me 👍🏻

**Pull request merged**
