### PR TITLE
macos ansible setup improvements

### PR DESCRIPTION
**Pull request by mahdipub**
unixPB: This PR is amed to add Xcode_offline which installs xcode without need to use any other 3rd party resource. Also some minor code changes and improvement added (e.g. install brew)

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [x] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [x] other documentation is changed or added (if applicable)
- [x] VPC/QPC not applicable for this PR

### CODE REVIEW

**Review by karianna — APPROVED** [review]

**Review by karianna — CHANGES_REQUESTED** [review]
Some unhappy YAML lint

**Review by sxa — COMMENTED** [review]
I've added a couple of other people as reviewers who are more knowledgeable about the macos stuff than I am but from a general perspective:
- At present we use the `main.yml` file for macos, so switching to use a separate one superficially feels like a slightly backwards step. Is it possible to integrate some of these changes into the normal execution of `main.yml` or is there a reason why you have chosen to do this as a separate top level file?
- This seems to have quite significant changes to some of the roles such as the ant-contrib one - are they specific to the goal of this PR to improve usability of the macos playbooks?
- Similarly this seems to change how things like the credentials are retrieved for the Jenkins_User role, which would be a change in behaviour.

Perhaps some of those things can be decoupled from this PR and proposed separately unless there is a reason they've all been put together.

**Comment by mahdipub** [comment]
> I've added a couple of other people as reviewers who are more knowledgeable about the macos stuff than I am but from a general perspective:
> 
> * At present we use the `main.yml` file for macos, so switching to use a separate one superficially feels like a slightly backwards step. Is it possible to integrate some of these changes into the normal execution of `main.yml` or is there a reason why you have chosen to do this as a separate top level file?
> * This seems to have quite significant changes to some of the roles such as the ant-contrib one - are they specific to the goal of this PR to improve usability of the macos playbooks?
> * Similarly this seems to change how things like the credentials are retrieved for the Jenkins_User role, which would be a change in behaviour.
> 
> Perhaps some of those things can be decoupled from this PR and proposed separately unless there is a reason they've all been put together.

- Yes. This file (including comments on the bottom) is only to show what are changes, and how does this whole works for macos. For sure we can combine them. 
- Yes. But at the same time they are general improvements in code and logic too. e.g in ant-contrib most of it is to introduce a new variable {{ ant_binary_file_name }} which lets avoid repetition of extracting the path every time we need. 
- Agreed. 
- Agreed. I can focus on xcode offline and then ask for the rest in separate PR.

**Comment by karianna** [comment]
@mahdipub Can you resolve the linter fixes?

**Comment by mahdipub** [comment]
Based on comments on slack, I will close this PR and split changes in 2~3 PRs. The one related to Xcode-offline and the other for brew is https://github.com/adoptium/infrastructure/pull/3417.

**Pull request closed without merging**
