### PR TITLE
unixPB: Add Centos8 Stream Support

### PR DESCRIPTION
**Pull request by steelhead31**
Fixes issue 2487

##### Checklist

- [X] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM

**Comment by sxa** [comment]
VPC run at https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1431/ - while this won't specifically test CentOS stream, I trust you've tested the changes on there, so the VPC run should validate that it hasn't broken the other platforms :-)

**Comment by steelhead31** [comment]
> VPC run at https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1431/ - while this won't specifically test CentOS stream, I trust you've tested the changes on there, so the VPC run should validate that it hasn't broken the other platforms :-)

@sxa
I've just tested a run of the original centos8 playbook on vagrant, what worked a week ago, doesnt work today... it appears the epel repository has had some packages removed and some renamed, as of 22nd May 2022, the python-selinux package has been renamed, and sshpass has been removed. I can fix both of these issues, would you rather I add another commit to this PR to fix original Centos8 or raise a new issue?

**Comment by sxa** [comment]
Re-running at https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1436/

**Comment by sxa** [comment]
Hmmm lots of failures in the docker role across the distributions ... I'll run again at https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1463/ - Not necessarily related to this PR but still a bit concerning if it's just sdtarted happening.

**Comment by sxa** [comment]
Re-running at https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1469 (That's going to take a while to be queued) with HOTSPOT instead of OpenJ9 since it looked like a few of the errors showing on the previous run may have been OpenJ9-specific.

**Review by sxa — APPROVED** [review]
LGTM on the basis of the VPC run

**Pull request merged**
