### PR TITLE
pbTests: Build bisheng as a test for RISC-V

### PR DESCRIPTION
**Pull request by sxa**
Bisheng is a hotspot variant that builds natively on the platform for RISC-V, so select that if we're going a hotspot build test in qemuPlaybookCheck

##### Checklist

- [ ] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md#commit-messages)
- [ ] [FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access) [J9/ppc64le](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/226/) and [hs/s390x](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/227/) (RISC-V QPC doesn't fully work yet)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Comment by Willsparker** [comment]
Do you have any documentation on Bisheng so I can read up? :-)

**Comment by sxa** [comment]
It's Huawei's port and was added via this issue: https://github.com/AdoptOpenJDK/openjdk-build/issues/2420

**Comment by sxa** [comment]
Assigning Will as co-owner of this since it can be used to fully test the RISC-V QPC support

**Comment by Willsparker** [comment]
Ah okay- in that case, this PR is blocked by #2123 - I'll get on that now

**Comment by sxa** [comment]
> Ah okay- in that case, this PR is blocked by #2123 - I'll get on that now

Yep that's pretty much why I've kept it in draft for now - awaiting the QPC test so we can verify it :-) Feel fre to take it out of draft as and when it's useful to do so

**Review by Willsparker — CHANGES_REQUESTED** [review]
`buildJDK.sh` will need an additional option to pass the variant - currently if building `openj9`, the `buildVariant` variable is set to nothing, and if building hotspot, it will pass `--hotspot` as an argument to `buildJDK.sh`. setting `buildVariant` to `bisheng` will just make `buildJDK.sh` error with unknown option.

**Comment by karianna** [comment]
@sxa Will need a rebase

**Comment by sxa** [comment]
I'm going to cancel this since Temurin now builds natively for JDK17+

**Pull request closed without merging**
