### PR TITLE
unixPb: Update Centos7 image with patch & texinfo to enabled building of devkit

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Fixes https://github.com/adoptium/infrastructure/issues/3289

DevKit creation needs:
- "patch" as DevKit patches certain downloads
- "texinfo" as DevKit build of binutils needs this to build

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [x] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
VPC job: https://ci.adoptium.net/job/VagrantPlaybookCheck/1823/

**Review by steelhead31 — APPROVED** [review]
LGTM

**Review by sxa — CHANGES_REQUESTED** [review]
Please add comments to indicate the reason for these additions e.g. "For devkit creation", similar to the one on strace so we don't lose track of why things that aren't directly related to the build are in here.
Also we need to have an equivalent change in the RHEL.yml that we can test on RHEL7 for s390x.

**Comment by andrew-m-leonard** [comment]
VPC job: https://ci.adoptium.net/job/VagrantPlaybookCheck/1825

**Comment by andrew-m-leonard** [comment]
> Please add comments to indicate the reason for these additions e.g. "For devkit creation", similar to the one on strace so we don't lose track of why things that aren't directly related to the build are in here. Also we need to have an equivalent change in the RHEL.yml that we can test on RHEL7 for s390x.

@sxa added comment and RedHat.yml update

**Review by sxa — APPROVED** [review]
LGTM thanks (Noting that VPC won't check RHEL specifically but I would expect it to be good and consistent with CentOS)

**Pull request merged**
