### PR TITLE
jenkinsfile: switch dockerfile push to use jenkins tooling

### PR DESCRIPTION
**Pull request by gdams**
##### Checklist

- [ ] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

fixes: https://github.com/adoptium/infrastructure/issues/2432

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM - does this need to land for the release?

**Review by sxa — COMMENTED** [review]
> LGTM - does this need to land for the release?

I think I'm leaning towards "No" now unless anyone knows of a good reason to merge before. Even though it's currently out of date, I think we need to ensure stabnility and I don't feel we need to run the risk of destabilising the releases with just a couple of working days to go, so in view of the fact we are in a "known good state" and have been looking at triage based on the existing builds, I vote hold off for now.

Also we still haven't had a clean run of [centos7_build_image_updater](https://ci.adoptopenjdk.net/job/centos7_docker_image_updater) - hopefully [#139](https://ci.adoptopenjdk.net/job/centos7_docker_image_updater/139) will go through ok.

**Comment by gdams** [comment]
Yup 139 went through successfully (and as you pointed out @sxa that's pushed the new image to dockerhub so we may as well merge here)

**Comment by sxa** [comment]
> Yup 139 went through successfully (and as you pointed out @sxa that's pushed the new image to dockerhub so we may as well merge here)

Can you run a set of pipelines on the Linux platforms to verify that there are no build breaks as a minimum please? Suggest merging once that is complete and verified to be ok.

**Comment by gdams** [comment]
> Can you run a set of pipelines on the Linux platforms to verify that there are no build breaks as a minimum please? Suggest merging once that is complete and verified to be ok.

Yeah it's only the aach64 pipeline that's using the Centos7 image but I can kick off some runs

**Comment by gdams** [comment]
All builds passed

**Pull request merged**
