### PR TITLE
docker: Remove out of support fedora and alpine dockerfiles

### PR DESCRIPTION
**Pull request by Haroon-Khel**
- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [x] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

fedora 33 and 34 are out of support https://docs.fedoraproject.org/en-US/releases/eol/
Alpine 312, 313 and 314 are out of support https://endoflife.date/alpine

The running containers will be replaced without the latest versions of both OSs, alpine 319 and fedora39

### CODE REVIEW

**Comment by Haroon-Khel** [comment]
The dockerstatic checker workflow will fail for the removed OSs

**Comment by sxa** [comment]
> The dockerstatic checker workflow will fail for the removed OSs

Surely they should be removed from https://github.com/adoptium/infrastructure/blob/master/.github/workflows/check_dockerstatic.yml in this PR too?

**Comment by Haroon-Khel** [comment]
I was saving it for another pr but yeah it makes sense to do it here

**Review by karianna — APPROVED** [review]

**Comment by karianna** [comment]
Should old Ubuntu versions also go?

**Comment by Haroon-Khel** [comment]
I believe the out of date ubuntu distros are being discussed here https://github.com/adoptium/infrastructure/issues/3393. The'r removal can be saved for another pr

**Comment by sxa** [comment]
> > Should old Ubuntu versions also go?

> I believe the out of date ubuntu distros are being discussed here #3393. Their removal can be saved for another pr

That's more about defining a policy and setting appropriate process in place going forward. We should certainly look at removing any old Ubuntu containers that we have at Temurin.

While I could be convinced either way I think we should leave the LTS Dockerfiles in the repository as long as Temurin can still run on them, especially since even Ubuntu 16.04 still has extended support if customers wish to pay Canonical for it until 2026 so is still viable if a customer with a suitable contract wished to use these dockerfiles to run an AQA suite. That would not be the case for the Fedora/Alpine versions being targeted by this PR.

**Review by steelhead31 — APPROVED** [review]
LGTM

**Pull request merged**
