### PR TITLE
github: Build on MacOS13 image in github workflow

### PR DESCRIPTION
**Pull request by Haroon-Khel**
- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [x] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

ref https://github.com/adoptium/infrastructure/issues/3203

### CODE REVIEW

**Comment by Haroon-Khel** [comment]
I've removed the `adoptopenjdk10` install from the common task as it is causing failures in both of the mac builds, and jdk10 get installed during the `adoptopenjdk_install` role

https://github.com/adoptium/infrastructure/blob/285558d486dfdbd8cf9b442dc2aef090f536385e/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml#L322

**Comment by karianna** [comment]
@Haroon-Khel GH Check fails...

**Comment by Haroon-Khel** [comment]
Reran the macos builds, looks like the gpg signature check fails intermittently with `no route to host` when trying to look up keys on the https://keyserver.ubuntu.com/ server

**Comment by Haroon-Khel** [comment]
The macos13 check passes

**Review by gdams — APPROVED** [review]

**Pull request merged**
