### PR TITLE
inventory: Add win2022 machines and update windows docs for installing jenkins agent as a service.

### LINKED ISSUE #2938: New Machine requirement: Windows server 2022 build systems
I need to request a new machine: As discussed in this week's PMC meeting we intende to move from building on Windows Server 2012 to the latest version now that @andrew-m-leonard has determined that we can produce binary identical builds of the latest JDKs across both versions.

- New machine operating system (e.g. linux/windows/macos/solaris/aix): windows
- New machine architecture (e.g. x64/aarch32/arm32/ppc64/ppc64le/sparc): x64
- Provider (leave blank if it does not matter): Azure
- Desired usage: build (and some test!)
- Any unusual specification/setup required: We'll want to use the VS2019 fixed layout for the install
- How many of them are required: 2 for build, maybe more for test (to replace existing ones)

Please explain what this machine is needed for: Building and testing Windows Server 2022 when 2012 goes out of support later this year.

### PR DESCRIPTION
**Pull request by steelhead31**
Fixes #2938 

Add new windows 2022 machines to inventory, and update the windows playbook documentation on how to install the jenkins agent as a service.

##### Checklist

- [X] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [X] other documentation is changed or added (if applicable)
- [X] VPC/QPC not applicable for this PR
- [X] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

Jenkins : https://ci.adoptium.net/computer/build-azure-win2022-x64-1/ & https://ci.adoptium.net/computer/build-azure-win2022-x64-2/
Nagios :  https://nagios.adoptopenjdk.net/nagios/cgi-bin/extinfo.cgi?type=1&host=build-azure-win2022-x64-1 & https://nagios.adoptopenjdk.net/nagios/cgi-bin/extinfo.cgi?type=1&host=build-azure-win2022-x64-2

### CODE REVIEW

**Comment by gdams** [comment]
awesome work @steelhead31, I've got a playbook change which I'll PR shortly that would allow us to automate this. The main thing is storing the jenkins secret in the vendor_files for each server so we can inject it into the template

**Comment by gdams** [comment]
> awesome work @steelhead31, I've got a playbook change which I'll PR shortly that would allow us to automate this. The main thing is storing the jenkins secret in the vendor_files for each server so we can inject it into the template

See https://github.com/adoptium/infrastructure/pull/2994

**Review by gdams — APPROVED** [review]

**Review by karianna — APPROVED** [review]

**Review by sxa — APPROVED** [review]

**Pull request merged**
