### PR TITLE
pbTests: fix vagrant playbook checker

### PR DESCRIPTION
**Pull request by gdams**
Fixes: https://github.com/adoptium/infrastructure/issues/2215

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [x] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

Vagrant PB test run: https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1186/

### CODE REVIEW

**Comment by karianna** [comment]
IIRC the linting problems were fixed in another PR so does this need rebasing?

**Comment by gdams** [comment]
@karianna I don't see any linting problems?

**Comment by sxa** [comment]
Bear in mind this may need more changes to avoid further side effects - @Willsparker had started making updates in https://github.com/adoptium/infrastructure/pull/2216.

The VPC run failed due to an OpenJ9 compilation failure. I've kicked off another VPC run without build or test at https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/1188/

**Comment by sxa** [comment]
In addition to the previous comment about #2216 this will need rebasing to pick up https://github.com/adoptium/infrastructure/pull/2230 so it can be tested properly.

**Comment by sxa** [comment]
Closing as incorporated into https://github.com/adoptium/infrastructure/pull/2216

**Pull request closed without merging**
