### PR TITLE
docs: update links

### PR DESCRIPTION
**Pull request by zdtsw**
##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [x] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [x] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM

**Review by jerboaa — APPROVED** [review]
LGTM

**Comment by sxa** [comment]
@zdtsw Just spotted a typo `termurin` instead of `temurin` ain the `cd` command at https://github.com/adoptium/infrastructure/pull/2523/files#diff-c7bd425fd98aad1f9fef20099637bcbdcfadeb566ba1f83bb40ce484f195b8cfR120 in this PR - can you submit another PR to change that please?

**Comment by zdtsw** [comment]
> @zdtsw Just spotted a typo `termurin` instead of `temurin` ain the `cd` command at https://github.com/adoptium/infrastructure/pull/2523/files#diff-c7bd425fd98aad1f9fef20099637bcbdcfadeb566ba1f83bb40ce484f195b8cfR120 in this PR - can you submit another PR to change that please?

sure!
https://github.com/adoptium/infrastructure/pull/2527

**Pull request merged**
