### PR TITLE
docker: Add centos7 to dockerstatic dockerfiles

### PR DESCRIPTION
**Pull request by Haroon-Khel**
- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [x] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

Security support for centos7 ends in June of this year, so its worth having a few containers on our machines until then
https://endoflife.date/centos

### CODE REVIEW

**Review by sxa — APPROVED** [review]
I didn't realise we didn't already have one of these so yeah if it is suitable for passing the tests I'm ok with adding it for a few months :-)

**Comment by Haroon-Khel** [comment]
Created https://ci.adoptium.net/computer/test-docker-centos7-x64-1/

**Review by karianna — DISMISSED** [review]

**Review by steelhead31 — CHANGES_REQUESTED** [review]
I suspect this will need the changes made here to update the eol centos7 repositories.. see this PR: [https://github.com/adoptium/infrastructure/pull/3647/files](https://github.com/adoptium/infrastructure/pull/3647/files) 

```
RUN sed -i -e 's!mirrorlist!#mirrorlist!g' /etc/yum.repos.d/CentOS-Base.repo

RUN if [ "$(uname -m)" = "aarch64" ]; then \
     echo "Running on arm64 architecture"; \
     sed -i 's|#baseurl=http://mirror.centos.org/altarch/\$releasever/|baseurl=http://vault.centos.org/altarch/7.9.2009/|' /etc/yum.repos.d/CentOS-Base.repo; \
   elif [ "$(uname -m)" = "ppc64le" ]; then \
     echo "Running on ppc64le architecture"; \
     sed -i 's|#baseurl=http://mirror.centos.org/altarch/\$releasever/|baseurl=http://vault.centos.org/altarch/7.9.2009/|' /etc/yum.repos.d/CentOS-Base.repo; \
   else \
     # Default To x64; \
     echo "Running on another architecture"; \
     sed -i -e 's!#baseurl=http://mirror.centos.org/centos/\$releasever!baseurl=https://vault.centos.org/7.9.2009/!g' /etc/yum.repos.d/CentOS-Base.repo; \
   fi
```

**Review by steelhead31 — APPROVED** [review]
Looks ok.

**Comment by Haroon-Khel** [comment]
Dont merge yet. I am adding steps to install git 2.15.0 form source since the latest git that can be installed on centos7 is 1.8 which is too old to run tests

**Pull request merged**
