### PR TITLE
unixPb: Link libffi.so.4 to libffi.so.6 in SLES12 s390x dockerfile

### PR DESCRIPTION
**Pull request by Haroon-Khel**
- [x] commit message has one of the [standard prefixes](https://github.com/adoptium/infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [faq.md](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptium.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptium.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] VPC/QPC not applicable for this PR
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

ref https://github.com/adoptium/infrastructure/issues/3026

Needed on sles 12 s390x to avoid this error on smoke tests
```
15:38:03  Run /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-s390x-temurin_SmokeTests/openjdkbinary/j2sdk-image/bin/java -version
15:38:03  =JAVA VERSION OUTPUT BEGIN=
15:38:03  Error: dl failure on line 894
15:38:03  Error: failed /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-s390x-temurin_SmokeTests/openjdkbinary/j2sdk-image/jre/lib/s390x/server/libjvm.so, because libffi.so.6: cannot open shared object file: No such file or directory
```

After the link is in place, the smoke test passes https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-s390x-temurin_SmokeTests/182/console

### CODE REVIEW

**Review by sxa — APPROVED** [review]

**Review by sxa — CHANGES_REQUESTED** [review]
Correction: Can you update the commit to have a suitable prefix please

**Review by karianna — APPROVED** [review]
Worth adding a comment as to why?

**Review by sxa — APPROVED** [review]

**Review by steelhead31 — APPROVED** [review]
LGTM

**Pull request merged**
